### ISSUE TITLE
sample videos are incorrectly IDd as multipart 

### ISSUE THREAD

**Issue by psouza4** [psouza4/mediacentermaster#1117]
Originally reported on Google Code with ID 1119
```
What steps will reproduce the issue?
1.download a torrent that includes a sample video as well as the movie title
c\download\movie1999abcdef\movie1999abcdef.mp4 big file size
c\download\movie1999abcdef\samplemovie1999abcdef.mp4 small file size

2.with folder cleaning on MCM will ID the sample as part 2 or similar instead of cleaning
it

3. end folder has
c\download\movie (1999)\movie (1999) part 1.mp4 big file size
c\download\movie (1999)\movie (1999) part 2.mp4 small file size



What is the exact version of the Media Center Master that you are using?
201.20512.555


Please provide any additional information below:
theres no convention in torrents other than the string 'sample' being somewhere in
the filename
```

Reported by `stevemckin` on 2012-07-26 00:36:30

**Comment by arvobowen** [comment]
Thanks for adding this, seems this is becoming an issue for me to.  Instead of adding it as a multi part title it adds TWO titles for me.  Just remove all video files under a threshold given as a setting maybe?

**Comment by robleedes** [comment]
Related forum topic links

[sample + uploader intro vid + movie mis-handled as multipart](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=10575&hilit=sample)

[Getting rid of unwanted small movie clips](http://forums.mediacentermaster.com/viewtopic.php?f=4&t=11155)

**Comment by psouza4** [comment]
This issue is superseded by issue #1709, which adds a customizable blacklist for the download parser to prevent sample files from being treated as multipart video releases.
