### ISSUE TITLE
Write keyword tags to Kodi/XBMC NFO metadata

### ISSUE THREAD

**Issue by psouza4** [psouza4/mediacentermaster#1610]
Originally reported on Google Code with ID 1615

```
As per
http://kodi.wiki/view/Video_library_tags

Allow the creation of custom collections, then writing respective tags to the nfo file
    <tag>Collection</tag>
```

Reported by `simoncarr79` on 2014-12-15 18:11:42

**Comment by Valdimarsson** [comment]
This would be a neat feature. Can see in the forum that there are others with the same problem. Hope you have the time to make it happen. http://forums.mediacentermaster.com/viewtopic.php?f=4&t=10460&hilit=Nfo+tags&start=10

**Comment by psouza4** [comment]
Keyword tags exist in Kodi/XBMC metadata as of several releases ago now.
