### ISSUE TITLE
Theme music downloader source change

### ISSUE THREAD

**Issue by jellovator** [psouza4/mediacentermaster#1678]
As posted at http://forums.mediacentermaster.com/viewtopic.php?f=6&t=10936

I believe the search url has changed from http://televisiontunes.com/search.php?seaWords="" to http://televisiontunes.com/search.php?s=""

Thanks!

**Comment by psouza4** [comment]
Thanks for being thorough -- sorry it took so long to look into this!

**Comment by psouza4** [comment]
Fixed and waiting for next release.
