### ISSUE TITLE
Add support for asx and strm files

### ISSUE THREAD

**Issue by dbalzan** [psouza4/mediacentermaster#1679]
Remote media (such as those on DLNA, Netflix, Hulu etc) are commonly accessed through asx and strm files.  MCE has support for the former and KODI support for the latter.

Currently MCM correctly populates metadata for 'asx' Movie files but ignores them for TV episodes.

Please can you add support for these file extensions?  At the moment, users need to workaround by renaming them to something else (e.g. mkv) and then back to asx.

http://forums.mediacentermaster.com/viewtopic.php?f=5&t=10932
http://forums.mediacentermaster.com/viewtopic.php?f=7&t=6070

**Comment by psouza4** [comment]
Added and waiting for next release.
