### ISSUE TITLE
Add proxy info to Support Information

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1682]
Forum topic link

[Issues fetching](http://forums.mediacentermaster.com/viewtopic.php?f=4&t=8235&p=34803&hilit=+general%2Foperating+environment#p34803)

In the above topic it was suggest to add a feature request.  I have searched using, "proxy info" "proxy information" and "support information" with no results.

**Comment by psouza4** [comment]
Added and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.14 build 32215.810 (2.14.32215.810).
