### ISSUE TITLE
Exclude tv series from subtitle search?

### ISSUE THREAD

**Issue by Valdimarsson** [psouza4/mediacentermaster#1684]
As the title says it would be nice to have a check/uncheck in metadata under every series to search for subtitles or stop searching. When a series is old there's little chance that someone adds new subtitles, especially in foreign languages.

Forum discussion on the matter:
http://forums.mediacentermaster.com/viewtopic.php?f=4&t=10489&p=43777

**Comment by psouza4** [comment]
Added and waiting for next release.
