### ISSUE TITLE
Can't fetch episodes using air dates (non-downloads parser)

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1686]
When a series title "Airing schedule" has been changed to "Daily":

* The program will not recognize or fetch episode files with just the date in the file name if it is in a season folder.

  * Example:  Show Title\Season 2\The Tonight Show Starring Jimmy Fallon - 2015-09-02.mp4

* The program will not process files through the "Watch" folder when they include an airing date and a season/episode identifier, with the date being listed first.

  * Example:  Watch folder\The Tonight Show Starring Jimmy Fallon - 2015-08-19 - S02E131.mp4

See:  [Forum post subject: Aired date problems](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=10986&p=43810#p43810) for more information.

**Comment by psouza4** [comment]
Fixed and waiting for next release.

**Comment by psouza4** [comment]
Re-opened based on notes here:

http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11000

**Comment by psouza4** [comment]
Fixed again and waiting for next release.
