### ISSUE TITLE
tvtunes search query change and HTML source change, no downloads

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1694]
Quote by Pete
Confirmed new source change: not only did they change their search page query string but also the HTML source on the page is different, so no results are identified.

Please enter to the Issue Tracker.

Forum post subject: [Update patch not working, re: "Theme music not downloading"](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11001&p=43915#p43915)

**Comment by psouza4** [comment]
Fixed and waiting for next release.
