### ISSUE TITLE
Latest update broke AAA

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1696]
Quote from Pete:

Verified bug -- sorry!

Will fix in the next release. Will you please add this to the Issue Tracker?

See Post subject: [Latest update broke AAA](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11010) for more information.

**Comment by psouza4** [comment]
Fixed and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.14.25615.885.
