### ISSUE TITLE
Add note to "Remotely add ... ... using uTorrent API" settings in uTorrent tab

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1698]
Add a note such as: (not required or do not use, if uTorrent and Media Center Master are installed on same computer) next to the two (2) settings.

Reasoning:

Your uTorrent video guide uses MCM v2.07.  These settings were not available in that version.

The uTorrent tab "Overview/Introduction note in the current version of MCM does not give any specifics to these two setting.  If it did, it could be overlooked by users who are rushing through set-up configuration steps.

**Comment by psouza4** [comment]
Depending on the version of uTorrent and sources, this setting is perfectly fine to use in an all-local environment.  I did myself for several months before moving uTorrent to a separate box (so that box can always run a VPN).  I'm not sure there's any need to amend this just yet.
