### ISSUE TITLE
Add "EpisodeNumberEnd" for multi-episodes - Feature Request

### ISSUE THREAD

**Issue by Happy2Play** [psouza4/mediacentermaster#1702]
Can the episode xml be updated with the "EpisodeNumberEnd" for multi-episodes, so both episodes will be properly identified in MediaBrowser/Emby.

http://forums.mediacentermaster.com/viewtopic.php?f=5&t=10582

**Comment by Happy2Play** [comment]
Any chance this could be added to xml to reflect both episodes when read.

**Comment by psouza4** [comment]
Field added for multi-episode metadata XML files.

Feature added and waiting for next release.

**Comment by psouza4** [comment]
Released update in version 2.17.26917.859.
