### ISSUE TITLE
Edit request for "Bad episode downloads should be:" 

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1703]
Reason for change: To fully communicate to the users that the available options are used for movie and episode downloads.

S&P > Download Parser tab > "Bad episode downloads should be:"

Remove "episode" from the description for the options, i.e., "Bad downloads should be:"

or

Add "movie and/or" to the description for the options, i.e., "Bad **movie and/or** episode downloads should be:"

 Reference:
See forum post subject: ["Official Video Torrents, uTorrent, and movie downloads"](http://forums.mediacentermaster.com/viewtopic.php?f=28&t=7440) video at 6:04.

**Comment by robleedes** [comment]
The options for "Bad episode downloads should be:" are not working for movies.

See forum post subject: ["Are options for "Bad episode downloads ..." also for movies?"](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11075) for more details.

**Comment by psouza4** [comment]
I replied in the forum topic: this feature isn't designed for episodes and can't easily be adapted because of the wide options for movies.
