### ISSUE TITLE
S&P setting removal request: "Automatically shrink WMC ... to thumbnail size (150x225)"

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1704]
S&P -> Artwork -> Automatically shrink WMC ... to thumbnail size (150x225)

If I am understanding correctly, the above setting is no longer needed, because of the "Automatically resize artwork ... after a meta-data fetch" setting does the same thing, i.e., redundant process.

If it is obsolete, it should be removed as an available option

Reference:
See forum post subject: ["Auto-shrink WMC?"](http://forums.mediacentermaster.com/viewtopic.php?f=7&t=3787&hilit=+automatic+image) for more information.

**Comment by psouza4** [comment]
This is not an obsolete feature.  This controls the poster thumb image size saved to the eHome directory for Windows Media Center (WMC) and not the base poster image size.

With this option disabled (and WMC metadata enabled), image files are copied to the eHome directory at their original size (and/or scaled size according to overall artwork size restrictions).

With this option enabled (and WMC metadata enabled), image files are reduced to a specific, optimized size when copied to the eHome directory.  The original poster image in the media folder is unaffected and retains its original size or overall artwork restricted size.
