### ISSUE TITLE
Bug report: the <MCMDateCutoff> isn't read into cache after a restore

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1705]
See forum post subject: ["What's black and white and [s]read[/s] red all over?"](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11061) for more information.

**Comment by psouza4** [comment]
This isn't correct, I can verify the data is correctly read.  Perhaps the XML was cached and needed to be refreshed.  Simply refreshing the title would verify this and if so, a full cache rebuild would resolve the user's issue.  I can't verify this as a bug.
