### ISSUE TITLE
Create a file blacklist for parser

### ISSUE THREAD

**Issue by jordanread** [psouza4/mediacentermaster#1709]
Create a user editable configuration file (JSON, XML,etc) to be processed for a blacklist of files to be deleted and ignored while parsing movies and tv shows. The blacklist will be a string value, and depending on code implementation, may support .Net regular expressions.

**Comment by psouza4** [comment]
A blacklist has been added which will be case-insensitive and support asterisked wildcard conventions, which should cover most use cases.  The blacklisted files will be deleted during the first stage of the download parser (and respects the preview mode without deletion for test purposes).

Feature added and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.14 build 32215.810 (2.14.32215.810).
