### ISSUE TITLE
Fanart.tv Source Change Newer API

### ISSUE THREAD

**Issue by mick1155** [psouza4/mediacentermaster#1710]
Fanart.tv is not fetching properly as they have changed something with the API server

http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11141&p=44695

**Comment by Happy2Play** [comment]
News letter on Fanart.tv

https://fanart.tv/newsletter/fanart-tv-api-changes

**Comment by psouza4** [comment]
Thanks for the references.  I've updated FanArt.tv support in MCM to use API v3.

Fixed and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.14 build 32215.810 (2.14.32215.810).
