### ISSUE TITLE
Re-order the Folder Cleaning options to make Clean In Preview Mode more noticeable

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1712]
Related Forum topic

[Media Center Master Deleted All My Movie Files](http://forums.mediacentermaster.com/viewtopic.php?f=4&t=11154)

Move the "Clean in test/preview mode" option to the top of the list, so user will see it, first, not miss it.

**Comment by psouza4** [comment]
Moved it to the top of the Folder Cleaning list, boldfaced it, and changed the text slightly.

Changed and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.14 build 32215.810 (2.14.32215.810).
