### ISSUE TITLE
MCM removing files from uTorrent prematurely

### ISSUE THREAD

**Issue by ticalthepimp** [psouza4/mediacentermaster#1713]
I have the settings in MCM under the uTorrent tab set as follows:

Automatically clear seeding & finished torrents is CHECKED
Do not clear torrents that have a seeding ETA is CHECKED
Do not clear torrents until share ratio reaches at least: is 1.500

I believe this to be correct in terms of settings but it's not working & hasn't been for months. Below is the last 2 lines of the log that shows this. It says it's not being removed because it has seeding time left, but then removes it 5 minutes later anyway.

4:15 PM :: MCM: Torrent XXXXXXXXXX.HDRip.XviD.AC3-EVO has finished, but isn't being removed because it is seeding and has 03:15:39 remaining.
4:20 PM :: MCM: Torrent XXXXXXXXXX.HDRip.XviD.AC3-EVO has finished and has been removed from uTorrent's list.

[b][u]Support Information generated by Media Center Master[/u]:[/b]
[spoil]Installation name: Media Center Master
Installation date: 20150807
Media Center Master: 2.14.25615.885
Windows version: Windows 10 Pro (64-bit)
Windows version (raw): Microsoft Windows NT 6.2.9200.0
.NET framework information:
[tab=30]Runtime loaded: 2.0.50727.8669
[tab=30]Runtimes installed:
[tab=30][tab=30]2.0.50727.4927 SP2
[tab=30][tab=30]3.0.30729.4926 SP2
[tab=30][tab=30]3.5.30729.4926 SP1
[tab=30][tab=30]4.6.00079
[tab=30][tab=30]4.0.0.0
AppData path: C:\Users\House\AppData\Roaming\Peter Souza IV\Media Center Master
AppSettingKey path: HKEY_CURRENT_USER\SOFTWARE\Peter Souza IV\Media Center Master
Command line: "C:\Program Files (x86)\Media Center Master\MCMStubLauncher.exe" /skipUAC
Current path: C:\Program Files (x86)\Media Center Master
Administrative details:
[tab=30]User is administrator: true
[tab=30]UAC status: enabled
[tab=30]Elevation status: elevated
[/spoil]

[b][u]Media Center Master preferences and settings (from registry)[/u]:[/b]
[spoil][tab=30]AllowSlowUIColumns: False
[tab=30]AnnouncementsLast: 1401473239
[tab=30]AppendParentalRatingsToMovieDescription: False
[tab=30]Art_AutoResize: False
[tab=30]Art_BackdropWidth: 1280
[tab=30]Art_EnableOldArtChooser: True
[tab=30]Art_PosterWidth: 320
[tab=30]Art_SeenNoPromptDisclaimer: True
[tab=30]Artwork_FanartTV: True
[tab=30]Artwork_FanartTV_ClearArt: True
[tab=30]Artwork_FanartTV_ClearArt_SaveAs: clearart
[tab=30]Artwork_FanartTV_ClearLogo: True
[tab=30]Artwork_FanartTV_DiscArt: True
[tab=30]Artwork_FanartTV_DiscArt_SaveAs: disc
[tab=30]Artwork_FanartTV_HD: True
[tab=30]Artwork_FanartTV_Logo_SaveAs: logo
[tab=30]Artwork_FanartTV_MovieBanner: True
[tab=30]Artwork_FanartTV_MovieBanner_SaveAs: banner
[tab=30]Artwork_FanartTV_Thumbnail: True
[tab=30]Artwork_FanartTV_Thumbnail_SaveAs: thumb
[tab=30]AskForIMDBIDOnUnknownMovies: True
[tab=30]AutoFetchMetaDataForTVScanFolders: True
[tab=30]AutoMaximizePosterWindow: False
[tab=30]AutoProcess_Fetch: True
[tab=30]AutoProcess_Move: True
[tab=30]AutoProcess_Rename: True
[tab=30]AutoProcessNewTV: True
[tab=30]AutoRunNewMediaList: True
[tab=30]AutoShrinkPostersForDVDID: False
[tab=30]BestSummary: Use primary fetcher's "outline" (short)
[tab=30]ConfirmationPromptTimeout: 30
[tab=30]CreateBlank: True
[tab=30]CreateDVDIDMetaData: False
[tab=30]CreateMovieNFOMetaData: True
[tab=30]CreatePyTiVoMetadata: False
[tab=30]DeepInspectVideoFor3D: False
[tab=30]DetectAndOrganizeSingleFileItems: True
[tab=30]DisableTorrenting: False
[tab=30]DontSaveWorkingCache: False
[tab=30]DontTryToElevateUAC: False
[tab=30]DotNetCheck_Status: Pass
[tab=30]Download_ParserInTestMode: False
[tab=30]DownloadAllBackdrops: False
[tab=30]DownloadCastThumbs: True
[tab=30]DownloadCrewThumbs: False
[tab=30]Downloader_AcceptArchives: True
[tab=30]Downloader_AgeThreshold: 4
[tab=30]Downloader_AllowAVI: True
[tab=30]Downloader_AllowFLV: False
[tab=30]Downloader_AllowMKV: True
[tab=30]Downloader_AllowMP4: True
[tab=30]Downloader_AllowMPG: True
[tab=30]Downloader_AllowWMV: True
[tab=30]Downloader_AvoidSubs: True
[tab=30]Downloader_Avoidx264: False
[tab=30]Downloader_CleanUp: True
[tab=30]Downloader_ExtractArchives: True
[tab=30]Downloader_InspectTrackers: True
[tab=30]Downloader_Movie_1080HD_SizeMax: 15000000000
[tab=30]Downloader_Movie_1080HD_SizeMin: 800000000
[tab=30]Downloader_Movie_720HD_SizeMax: 15000000000
[tab=30]Downloader_Movie_720HD_SizeMin: 800000000
[tab=30]Downloader_Movie_SD_SizeMax: 2000000000
[tab=30]Downloader_Movie_SD_SizeMin: 300000000
[tab=30]Downloader_MovieAllowForeign: False
[tab=30]Downloader_MovieExcludeTerms: cam r5 ts telesync webscr* dubbed russian german fr french dutch* swesub* vosfr nlsubs nl_subs dvd4 dvd5 dvd9
[tab=30]Downloader_MovieExcludeTerms_1080HD: 720*
[tab=30]Downloader_MovieExcludeTerms_720HD: 1080*
[tab=30]Downloader_MovieExcludeTerms_SD: 720* 1080*
[tab=30]Downloader_MovieIncludeTerms_1080HD: 1080*
[tab=30]Downloader_MovieIncludeTerms_720HD: 720*
[tab=30]Downloader_MovieQuality: 15
[tab=30]Downloader_ParserIgnoresReadOnly: True
[tab=30]Downloader_RatingThreshold: 4.5
[tab=30]Downloader_ReplaceUseBestQuality: True
[tab=30]Downloader_RunAtStartup: False
[tab=30]Downloader_TV_1080HD_SizeMax: 8000000000
[tab=30]Downloader_TV_1080HD_SizeMin: 500000000
[tab=30]Downloader_TV_720HD_SizeMax: 4000000000
[tab=30]Downloader_TV_720HD_SizeMin: 200000000
[tab=30]Downloader_TV_SD_SizeMax: 1250000000
[tab=30]Downloader_TV_SD_SizeMin: 70000000
[tab=30]Downloader_TVAllowForeign: False
[tab=30]Downloader_TVExcludeTerms: preair flv dubbed german fr french dutch* swesub* vosfr nlsubs nl_subs dvd4 dvd5 dvd9
[tab=30]Downloader_TVExcludeTerms_1080HD: 720*
[tab=30]Downloader_TVExcludeTerms_720HD: 1080*
[tab=30]Downloader_TVExcludeTerms_SD: 720* 1080*
[tab=30]Downloader_TVIncludeTerms_1080HD: 1080*
[tab=30]Downloader_TVIncludeTerms_720HD: 720*
[tab=30]Downloader_TVQuality: 15
[tab=30]Downloader_UpgradeMovieQuality: True
[tab=30]Downloader_WantObscure: False
[tab=30]DownloadHistory_Library: False
[tab=30]DownloadHistory_Movies: True
[tab=30]DownloadHistory_NotFound: True
[tab=30]DownloadHistory_Skip: False
[tab=30]DownloadHistory_Success: False
[tab=30]DownloadHistory_TV: True
[tab=30]DualPass: True
[tab=30]EpisodeRenamingConvention: N - SXXEYY - T
[tab=30]ErrorReporting: 1
[tab=30]FolderCleaner_AutoCleanOnFetch: True
[tab=30]FolderCleaner_DeleteSamples: True
[tab=30]FolderCleaner_DeleteStaleMetadata: True
[tab=30]FolderCleaner_DeleteUnknownFolders: True
[tab=30]FolderCleaner_DeleteUnknownImages: True
[tab=30]FolderCleaner_DeleteUnusedExternalMetadata: True
[tab=30]FolderCleaner_TestMode: False
[tab=30]ForcedTitleTag: True
[tab=30]HasSeenTooltipOnMinimize: True
[tab=30]HideTitleBarLicensing: False
[tab=30]HighlightMissingMeta: True
[tab=30]HTML_FastVideoInspection: True
[tab=30]IgnorePeriodFilesAndDirectories: True
[tab=30]ImagesByNameMode: New
[tab=30]Interval_AutoScan: 7200
[tab=30]Interval_AutoScanEpisodes: 7200
[tab=30]Interval_DownloadNewMovies: 7200
[tab=30]Interval_DownloadNewTV: 7200
[tab=30]Interval_DownloadParser: 3600
[tab=30]Interval_DownloadTorrentFeeds: 3600
[tab=30]Interval_NewMediaList: 7200
[tab=30]Interval_uTorrent: 300
[tab=30]LastFetchMode: 1
[tab=30]LicenseCache: SVAfg*******************
[tab=30]LicenseCode: MCMLT******************
[tab=30]LicenseDetails: {Privacy Censor}
[tab=30]LicensingMode: 2
[tab=30]LicensingSystemNew: True
[tab=30]LimitBackdropDownloads: 5
[tab=30]LogLimit: 5000
[tab=30]LogTimestamp: True
[tab=30]LogToFile: True
[tab=30]ManualMovieConfirm: True
[tab=30]MaxFetcherThreads: 8
[tab=30]MCMInstallCheck: 1
[tab=30]MediaListSort: ListTitle_Standard/A
[tab=30]Metadata_AllowFetcherKeywordTags: True
[tab=30]Metadata_aTVFlash: False
[tab=30]Metadata_Boxee: False
[tab=30]Metadata_DLNA: False
[tab=30]Metadata_Embedded: False
[tab=30]Metadata_FullOverwrite: True
[tab=30]Metadata_JRiver: False
[tab=30]Metadata_MediaBrowserOld: False
[tab=30]Metadata_MythTV: False
[tab=30]Metadata_WDTV: False
[tab=30]Metadata_XStreamer: False
[tab=30]MinimizeToTray: True
[tab=30]MoreRelaxedSearching: True
[tab=30]MoveMovieDownloadsTo: E:\Media\Movies
[tab=30]Movie_VotedScoreSource: imdb.com
[tab=30]Netgear_AutoReduceFileSize: True
[tab=30]Netgear_CompatibleTextFields: False
[tab=30]Netgear_EmbedPoster: True
[tab=30]Netgear_Force_EASCII: True
[tab=30]Netgear_MetaData: False
[tab=30]Netgear_TLENID3Standard: True
[tab=30]NewMediaListDays: 7
[tab=30]NMTPathMapping: C:\Example\Path**file:///opt/sybhttpd/localhost.drives/NETWORK_SHARE/EXAMPLESHARE|
[tab=30]NoCommas: True
[tab=30]NoConfirmOnOneResult: True
[tab=30]NonblockingConfirmationPrompts: True
[tab=30]NoSpaces: False
[tab=30]NoSpaces2: False
[tab=30]OnlyShowAnnouncements: False
[tab=30]OrganizerShowMetaData: True
[tab=30]OrganizerShowOtherFiles: True
[tab=30]Plugin_Fetcher_Adult: AdultDVDEmpire
[tab=30]Plugin_Fetcher_Movies1: IMDB
[tab=30]Plugin_Fetcher_Movies2: TMDb
[tab=30]Plugin_Fetcher_TV: thetvdb.com
[tab=30]PopupMoveWindow: True
[tab=30]PostProcessing_Hide: True
[tab=30]PostProcessing_Wait: True
[tab=30]PostProcessingTVEpisode_Hide: True
[tab=30]PostProcessingTVEpisode_Wait: True
[tab=30]PostProcessingTVShow_Hide: True
[tab=30]PostProcessingTVShow_Wait: True
[tab=30]ReadOnlyFoldersVisible: True
[tab=30]RelaxedTVDetection: True
[tab=30]RenameFiles: True
[tab=30]RenameFolders: True
[tab=30]Renamer_Movie: T T
[tab=30]Renamer_Series: T T
[tab=30]RenamerDownloadStyle: False
[tab=30]RespectIDs: True
[tab=30]RuT_EnableManager: False
[tab=30]ScanFolders: E:\Media\Movies|E:\Media\TV|E:\Media\Kids\Movies|E:\Media\Kids\TV
[tab=30]SeasonRenamingConvention: Season {S}
[tab=30]SortByOriginalFolder: False
[tab=30]SortWithoutArticle: False
[tab=30]Subtitle_NamingMode: Single
[tab=30]Subtitles_PreferedLanguage: in English
[tab=30]Subtitles_PreferedLanguages: en,en
[tab=30]ThemedBackgrounds: True
[tab=30]ThumbnailExtract_Auto: True
[tab=30]ThumbnailExtract_Lots: False
[tab=30]ThumbnailLocation: E:\Media\Thumbs
[tab=30]TMDb_CountryAbbreviation: US
[tab=30]TMDb_LanguageAbbreviation: en
[tab=30]TMDb_LanguageID: 7
[tab=30]TMDb_LanguageName: English
[tab=30]TorrentDownloadPath: E:\Downloads
[tab=30]TorrentDownloadPathOther: E:\Downloads
[tab=30]TorrentFinishedPath: E:\Downloads\Completed
[tab=30]Torrents_AllowMagnetLinks: True
[tab=30]Torrents_DisableVirusProtection: False
[tab=30]Torrents_DownloadDelay: 1
[tab=30]Trailers_AllowAdaptiveYouTubeTrailerMuxing: False
[tab=30]Trailers_AlwaysReEncode: False
[tab=30]Trailers_AutoDownload: False
[tab=30]Trailers_AutoReEncode: False
[tab=30]Trailers_AutoReplace: True
[tab=30]Trailers_MaxBitRate: 1600
[tab=30]Trailers_SaveLocation: 6
[tab=30]Trailers_TargetSize: 480 (pixels high)
[tab=30]Trailers_WatchOutput: False
[tab=30]Trakt: False
[tab=30]Trakt_Auto: False
[tab=30]Trakt_AutoAddTV: False
[tab=30]Trakt_AutoDownload: False
[tab=30]Trakt_AutoDownloadCheckRelease: True
[tab=30]Trakt_ReleaseDayOffset: 0
[tab=30]TranslateSEEtoAAA: False
[tab=30]TTVDB_LanguageAbbreviation: en
[tab=30]TTVDB_LanguageID: 7
[tab=30]TTVDB_LanguageName: English
[tab=30]TV_Overrides: law and order ci*71489*4203|mash*70994*4315|the office us*73244*6061
[tab=30]TVAutoScanCheckMissingThumbs: True
[tab=30]TVFetchSeasonBanners: True
[tab=30]TVFetchSeasonPosters: True
[tab=30]TVShowBias: US
[tab=30]TVThemeMusic: False
[tab=30]TVVideoBackdrops: False
[tab=30]UITheme: Windows
[tab=30]UpdateFile: Update.txt
[tab=30]UpdatePath: http://download.MediaCenterMaster.com/AutoUpdate/
[tab=30]UseAutoDetectionMode: True
[tab=30]UseAutoUpdate: True
[tab=30]UseCloudNetwork: True
[tab=30]UseConsolodatedGenres: False
[tab=30]UseExistingPosters: True
[tab=30]UseFetcherThreads: True
[tab=30]Usenet_AutoLoadNZB: False
[tab=30]Usenet_AutoLoadNZBPath: E:\Downloads\NZB
[tab=30]Usenet_Binsearch: False
[tab=30]Usenet_CacheLocation: C:\Users\House\AppData\Roaming\Peter Souza IV\Media Center Master\Usenet
[tab=30]Usenet_Host: us.news.astraweb.com
[tab=30]Usenet_MaxConnections: 20
[tab=30]Usenet_MCMIndex: True
[tab=30]Usenet_MoveNZBFile: True
[tab=30]Usenet_MoveNZBFilesTo: E:\Downloads\NZB
[tab=30]Usenet_NZBsu: False
[tab=30]Usenet_Password: {Privacy Censor}
[tab=30]Usenet_Port: 119
[tab=30]Usenet_SSL: False
[tab=30]Usenet_UseMCMToDownload: False
[tab=30]Usenet_UserName: {Privacy Censor}
[tab=30]UsePostProcessing: False
[tab=30]UsePostProcessingTVEpisode: False
[tab=30]UsePostProcessingTVShow: False
[tab=30]UseSecondaryGenres: False
[tab=30]UseWindowsProxy: True
[tab=30]UT_AutoForceTVDownloads: False
[tab=30]UT_AutoLabel: False
[tab=30]UT_AutoRemoveCompletes: True
[tab=30]UT_AutoRepair: True
[tab=30]UT_ConsistentKB: True
[tab=30]UT_EnableManager: True
[tab=30]UT_Hostname: localhost
[tab=30]UT_LeaveSeedingTorrentsWithETA: True
[tab=30]UT_Password: {Privacy Censor}
[tab=30]UT_Port: 11111
[tab=30]UT_RemoteAddMagnets: False
[tab=30]UT_RemoteAddTorrents: False
[tab=30]UT_SeedUntilRatio: 1.500
[tab=30]UT_Username: {Privacy Censor}
[tab=30]VersionUpgrader: 4
[tab=30]WantExtendedTVStatus: True
[tab=30]WantMovieTorrentDownloader: True
[tab=30]WantNewMovieDownloads: False
[tab=30]WantOpenSubtitlesOrg: False
[tab=30]WantQueueAbortConfirmation: True
[tab=30]WantSmoothImages: False
[tab=30]WantSubtitleDownloads: True
[tab=30]WantSubtitleDownloads_Movies: True
[tab=30]WantSubtitleDownloads_TV: False
[tab=30]WantTorrent_eztv: True
[tab=30]WantTorrent_kickasstorrents: True
[tab=30]WantTorrent_newtorrents: True
[tab=30]WantTorrent_rarbg: True
[tab=30]WantTorrent_thepiratebay: True
[tab=30]WantTorrent_thepiratebay_new: True
[tab=30]WantTorrent_torrentbutler: True
[tab=30]WantTorrentAutoStart: True
[tab=30]WantTVTorrentDownloader: True
[tab=30]WantUsenet: True
[tab=30]WantVideoDetails: True
[tab=30]WhatToDoWithBadEpisodeDownloads: Re-download
[tab=30]XBMC_AlternatePosterSize: False
[tab=30]XBMC_API_Host: 192.168.100.9
[tab=30]XBMC_API_Integration: True
[tab=30]XBMC_API_Notifications: False
[tab=30]XBMC_API_Password: {Privacy Censor}
[tab=30]XBMC_API_Port: 11
[tab=30]XBMC_API_Scan: False
[tab=30]XBMC_API_Username: {Privacy Censor}
[tab=30]XBMC_ExtraFanart: True
[tab=30]XBMC_FillTitleFromOriginalTitle: False
[tab=30]XBMC_GenerateFanArtwork: True
[tab=30]XBMC_GeneratePosterArtwork: True
[tab=30]XBMC_NeverDeleteExtraFanart: True
[tab=30]XBMC_SpecialsSeasonHackFix: True
[tab=30]XBMC_Version: 12
[tab=30]YAMJEnabled: False
[/spoil]

[b][u]Detailed Version Information[/u]:[/b]
[spoil]File versions (current + install path):
[tab=30]AutoUpdate.dll version: 2.30.34914.1417
[tab=30]MCMStubLauncher.exe version: 2.12.23514.782
[tab=30]unins000.exe version: 51.52.0.0
File versions (%AppData%\bin):
[tab=30]AdultDVDEmpire.dll version: 3.10.13415.794
[tab=30]AutoUpdate.dll version: 2.30.34914.1417
[tab=30]ffmpeg.exe version: none
[tab=30]GayDVDEmpire.dll version: 3.5.114.822
[tab=30]ICSharpCode.SharpZipLib.dll version: 0.86.0.518
[tab=30]IMDB.dll version: 3.3.11015.1380
[tab=30]Ionic.Zip.dll version: 1.9.1.8
[tab=30]MCMIDTag.dll version: 2.10.114.0
[tab=30]MCMMKVTag.dll version: 2.10.114.0
[tab=30]MCMWTV.dll version: 2.10.114.0
[tab=30]MediaCenterMaster.exe version: 2.14.25615.885
[tab=30]MediaInfo.dll version: 0.7.65.0
[tab=30]MonoTorrent.dll version: 0.80.0.0
[tab=30]Newtonsoft.Json.dll version: 5.0.5.16108
[tab=30]ObjectListView.dll version: 2.10.114.881
[tab=30]par2.exe version: none
[tab=30]RottenTomatoes.dll version: 1.2.19713.596
[tab=30]Sublight.Plugins.SubtitleProvider.dll version: 1.0.0.0
[tab=30]SublightPlugin.dll version: 2.13.34914.1417
[tab=30]System.Data.SQLite.dll version: 1.0.74.0
[tab=30]tMDB.dll version: 5.32.25415.922
[tab=30]TMDbA.dll version: 1.5.36113.600
[tab=30]unrar.dll version: 4.0.4.3
[tab=30]VidInfo.exe version: 2.15.25315.814
[/spoil]

**Comment by psouza4** [comment]
Your report requires debug information from uTorrent (which we can get from the developer-level debug option in the Help menu).  I suspect it is incorrectly reporting that a torrent has finished when it hasn't.

The JSON torrents list (list=1 API call) returns an array of torrents with an array of values indicating each torrent's status.  The 2nd value is the status expressed as a coded integer.  The 5th value is the completion percentage expressed as an integer x 10 (so 500 would be 50.0% complete).  The 8th value is the share ratio, for example, expressed as an integer x 1000 (so 500 would be 0.5 or 50% share ratio), as well the ETA is expressed in the 11th value as an integer indicating how many seconds uTorrent estimates until the share ratio is reached given current transfer rates.

It's uTorrent's job to correctly report these values.  Media Center Master checks the status of the torrent, which is the coded status ID in conjunction with the completion percentage.

A torrent is finished if it meets any of the following criteria:
status ID 136 with 100% completion ("Finished")
status ID 137 with 100% completion ("Seeding", usually forced-start seeding)
status ID 150 with 100% completion ("Finished")
status ID 152 with 100% completion ("Finished & Moved", technically an error that the files were moved so seeding can't continue)
status ID 200 with 100% completion ("Queued Seed")
status ID 201 with 100% completion ("Seeding", on its own)
status ID 999 with 100% completion ("Finished", only seen when a torrent has just finished downloading before moving to status ID 150)

Any other status, or under 100% completion, will cause the torrent to be skipped.  Once one of the criteria is met, various user settings are checked to see if it's eligible for removal:

If the option for leaving seeding torrents with an ETA is checked and the torrent has an ETA greater than 0, the torrent is skipped (with a message -- the one you see first in your log).

If the option for waiting until a seed ratio is greater than 0 and the torrent has a seed ratio that is lower than the user's preference, the torrent is skipped (with a message about the share ratio).

Getting this far means the torrent is eligible for removal, so the torrent is removed from the list (with a message about its removal -- the same message you see second in your log).

I've gone over the logic several times and don't see any mistakes, so if you're convinced there's an issue here, it will fall on you to present details and examples.
