### ISSUE TITLE
Episode Renaming Token for Absolute Numbers 

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1723]
The non-download parser should be able to process and rename animé files with absolute numbers in true animé style if they are all in a "Season 1" folder.

Add an episode renaming token for absolute numbers.

See forum post subject:  "Animé renaming question" [here](http://forums.mediacentermaster.com/viewtopic.php?f=4&t=11187) for more information.

**Comment by psouza4** [comment]
The rename tokens A, AA, and AAA will now output single-digit, double-digit, and triple-digit absolute/alternate numbering for shows.  If the episode does not have an absolute number, the default SxxEyy format will be used instead.

**Comment by psouza4** [comment]
Released in version 2.16.10117.1188.
