### ISSUE TITLE
Movie fetch aborted because trailers are counted toward the video file threshold limit

### ISSUE THREAD

**Issue by codexile** [psouza4/mediacentermaster#1724]
Example:

i have a folder "Captain America - Il primo vendicatore (2011) [SD]" with 
all posters and images inside, and with those video files:
Captain America - Il primo vendicatore (2011) [SD] part1.avi
Captain America - Il primo vendicatore (2011) [SD] part2.avi
Captain America - Il primo vendicatore (2011) [SD] part1-trailer.flv

all files were renamed, and the trailer was downloaded, by MCM, a the first "fetch"
if i now redo a fetch it states that there are too many video files.

regarding forum post:
http://forums.mediacentermaster.com/viewtopic.php?f=5&t=7069

Thanks!

**Comment by psouza4** [comment]
Should be fixed in the next version.
