### ISSUE TITLE
<VideoCodec>x264 does not display the H.264 media flag in Kodi

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1725]
MCM is using x264 as the video codec in the .xml files.  When this is exported to an .nfo file and used in Kodi, the H.264 media flag is not displayed.

See forum post subject: [Kodi does not respect x264 for video codec media flag](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11239) for more information.

**Comment by psouza4** [comment]
(1) There is a significant difference between x264 and H.264.  They are not synonymous.  H.264 is a specification, like MPEG2 or MPEG4p2.  x264 is an open-source codec for formatting video to H.264.  Media Center Master correctly writes the specific codec to the metadata when possible.

(2) Every skin in Kodi handles codecs, formats, and container types differently.  You may want to consult with the author of that skin, who has evidently not supported x264 as an H.264 format video in the design of their skin.  That's a skin author issue.
