### ISSUE TITLE
Minimum Seed Requirements Change

### ISSUE THREAD

**Issue by lloydie11** [psouza4/mediacentermaster#1726]
This is to track the issue raised at the below forum in relation to having an option to change the default SEED requirements, or to be able to bypass them for items that do not match them normally.

http://forums.mediacentermaster.com/viewtopic.php?f=5&t=10807&p=45277#p45277

**Comment by jgearheart390** [comment]
I strongly agree that this would be a very useful feature.  I would much rather have a torrent sitting in utorrent while it waits for seeds than have the log window and resource usage of MCM constantly rescanning the torrent sites looking for a match with 5 seeds.

**Comment by psouza4** [comment]
Feature added and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.15 build 1016.832 (2.15.1016.832).
