### ISSUE TITLE
iMDB Parental Guide MPAA rating problem

### ISSUE THREAD

**Issue by vvicked** [psouza4/mediacentermaster#1727]
Currently, if you append the Parental Guide information to movies, the MPAA rating always shows up as "NR".

For example:
Parental Rating Summary:
MPAA Rating: NR
Sex & Nudity: 0
Violence & Gore: 0
Profanity: There are some uses of mild language in the film, such as 'a**', 'h*ll', and 'd*mned'.
Alcohol/Drugs/Smoking: 0
Frightening/Intense Scenes: 2

The MPAA Rating value should look similar to these:
MPAA Rating: Rated PG-13 for some violence and brief strong language
MPAA Rating: Rated R for strong frontier combat and violence including gory images, a sexual assault, language and brief nudity

**Comment by Happy2Play** [comment]
Please post in the forum with a specific example, debug log, and support information.

**Comment by psouza4** [comment]
Closing as invalid -- sounds like you have an old version of IMDb.dll and should return to the support forums to troubleshoot.
