### ISSUE TITLE
Feature Request: Ability to convert magnet links (TPB) to locally saved .torrent files

### ISSUE THREAD

**Issue by dereckhall** [psouza4/mediacentermaster#1730]
I'm probably in the minority, but thought i'd request anyway after getting Pete's approval. i have a setup where basically MCM grabs the .torrent file once it matches and drops it in a local directory which is then picked by a remote deluge torrent client i sync with. the remote client will then process/download the torrent and deliver the final video back to MCM's directory that I have scheduled to be scanned with the download parser.

would it be possible or even worthwhile to implement the ability to automatically convert magnet links to .torrent files? this would make sites like TPB useful again for users with a similar setup.

I was finally able to get a functional Python script that utilizes libtorrent to do the conversion I mentioned above. Bolting something similar onto MCM will be slightly more difficult I'm sure.

Thanks!

**Comment by lloydie11** [comment]
I too would love this ability. More and more downloads are magnet links only.

**Comment by 00Asgaroth00** [comment]
I am a premium user and would love this feature too, I do a similar setup to the OP except I use my synology nas to do the downloading, it will only scan for .torrent files in its scan folder though.

I'm seeing more sites like rarbg are also preferring magnet links, so when MCM performs a check for new episodes, they are being excluded for download as "launch magnet links locally" is disabled in my settings. I have to manually download these torrent files in this case, which, unfortunately, is becoming more often than not.

If MCM would pull and convert the magnet link to a torrent file then put the saved torrent file in my "download" folder then DSM would scan and download the torrent and everything proceeds as normal.

**Comment by psouza4** [comment]
Most magnet links will now load as physical .torrent files by leveraging itorrents.org as a torrent cache service beginning in Media Center Master version 2.18.13418.831.

**Comment by psouza4** [comment]
Released in version 2.18 build 13418.831 (2.18.13418.831).

**Comment by Ollaff87** [comment]
Is there anything specific configuration needed to enable this feature, or is it on by defualt?  I use a deluge VM and am looking to save .torrent files to folder shared with the VM.  I see an option for where to save torrent files.  Does uTorrent integration need to be enabled for this to work?

Thanks for any input, I'd really like to implement this right away but don't have the time to experiment right now.

**Comment by psouza4** [comment]
It's automatic... you don't need to do anything for it to work, if a magnet link is available as a torrent via the hash-n-cache service itorrents.org, the.torrent will be used internally.  Nothing you need to do.

**Comment by AaronArgent** [comment]
cant see this itorrents.org hash-n-cache service, do you have a guide on how to set this up?
