### ISSUE TITLE
MCM creating movie.xml file for TV Series

### ISSUE THREAD

**Issue by muzicman61** [psouza4/mediacentermaster#1733]
MCM creates a movie.xml file for TV Series.  After the first episode in a season is processed, it will download the episode jpg and create a Netgear TAG file.  However, subsequent episodes when processed to not get their episode jpg downloaded or the Netgear TAG file created.  Seems like this started about 2 or 3 weeks ago.

**Comment by Happy2Play** [comment]
Affecting everyone using Netgear metadata.

http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11308

**Comment by psouza4** [comment]
I'm not sure why this would suddenly start happening, but I've added extra logic that prevents the automatic conversion of .TAG to .XML, which should prevent movie.xml being created for TV series for Netgear users.
