### ISSUE TITLE
Feature Request: Stop Searching for TV Shows with a 'Ended Status'

### ISSUE THREAD

**Issue by mattforte** [psouza4/mediacentermaster#1742]
Would be nice if MCM had an option to stop Searching for new Episodes on TV Shows that have a 'Air Status' of 'Ended'

Like a tick option:

'When a TV Show Status is set to ended, would you like MCM to stop searching for new episodes'

**Comment by psouza4** [comment]
This feature already exists in two ways:

(1) whenever the status of a show is ended or canceled, the show is skipped from the automatic "keep this show updated" process.  You can still search for new episodes manually, but it will be skipped from the automated/bulk process.

(2) whenever the score & status of a show is updated and it becomes ended or canceled, the "keep this show updated" is unticked automatically.  This kind of update is performed by right-clicking and choosing to update score and status from the selected title(s) or from the menus to perform the operation on your entire library.

Please make sure you follow our guidelines for requesting features ( http://www.mediacentermaster.com/support/ ) as there is a lot of functionality built into Media Center Master and it's easy to overlook how to get it to work the way you want.  The community forums are a great way to check with us on how to get something done using MCM.
