### ISSUE TITLE
Restore Backup fails with "&" in TV Override "NullRefernceException"

### ISSUE THREAD

**Issue by Happy2Play** [psouza4/mediacentermaster#1747]
If you have a TV Override with "&" in it  (ex. rizzoli & isles*161461*) you get Restore Fails.

NullRefernceException 
Object reference not set to an instance of an object.

http://forums.mediacentermaster.com/viewtopic.php?f=4&t=11536

**Comment by psouza4** [comment]
Fixed and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.15 build 20616.1399 (2.15.20616.1399).
