### ISSUE TITLE
Conflict with Ember generated NFO

### ISSUE THREAD

**Issue by hairyhippy** [psouza4/mediacentermaster#1748]
NFO generated has <id TMDB="39006">tt0075893</id> for example. Unfortunately when loading the files to MCM, it for some reason is reading this and isn't able to retrieve the correct metadata. However if I manually edit the NFO to <id>tt0075893</id> and reload MCM it has no issue.

I raised this issue their side and the response was http://forum.xbmc.org/showthread.php?ti ... pid1549244

**Comment by psouza4** [comment]
You didn't really provide enough info here.  What I'm guessing you mean is that if you export metadata from Emby to an NFO and have Media Center Master try to import it, Media Center Master fails if the movie ID is formatted in a specific way.  The way mentioned in the Emby forum (by the way, your link is broken -- try to make sure they work in the future) does work for me, but I've added additional logic to help it out in case of future issues.

**Comment by psouza4** [comment]
Updated and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.15 build 20616.1399 (2.15.20616.1399).

**Comment by hairyhippy** [comment]
Hi - This is not fixed.  Apologies I didn't provide enough info and also the link being "dead".  For me that link redirected to the new Kodi forum from the old XBMC forum.
My original post on the mediacenter forum is here:
http://forums.mediacentermaster.com/viewtopic.php?f=6&t=8310
And the link on Kodi forum:
http://forum.kodi.tv/showthread.php?tid=172394&pid=1549244#pid1549244

**Comment by hairyhippy** [comment]
Hi Peter - This is not fixed.  Apologies I didn't provide enough info and also the link being "dead".  For me that link redirected to the new Kodi forum from the old XBMC forum.
My original post on the mediacenter forum is here:
http://forums.mediacentermaster.com/viewtopic.php?f=6&t=8310
And the link on Kodi forum:
http://forum.kodi.tv/showthread.php?tid=172394&pid=1549244#pid1549244

Please let me know what else I can provide to help fix this.


________________________________
