### ISSUE TITLE
Download & HTML report start Date being lost

### ISSUE THREAD

**Issue by slyckmb** [psouza4/mediacentermaster#1749]
A valid date stored as "Download & HTML report start" will eventually be ignored by the downloader and missing episodes report generator.

The workaround is to uncheck/check/save the date for each affected series.

Refer to forum post:
[http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11495&hilit=download+html+report+start](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11495&hilit=download+html+report+start)

**Comment by Happy2Play** [comment]
Hyper link is broken but copy and paste that link takes you to the proper topic.

**Comment by slyckmb** [comment]
Ok, I fixed the link so it's clickable.

**Comment by psouza4** [comment]
Fixed and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.15 build 20616.1399 (2.15.20616.1399).
