### ISSUE TITLE
Multiple translations for the same language

### ISSUE THREAD

**Issue by cldborges** [psouza4/mediacentermaster#1750]
Hello.

A few months ago a problem appeared. When performing fetch the MCM translates the movie name to PT-pt, but I am Brazilian and I want update to PT-Br. As an example the Minions movie (https://www.themoviedb.org/movie/211672 ... uage=pt-PT), which in Brazil is known as Minions but Portugal is Minimos, then Mínimos is chosen and the name does not make sense in Brazil. I believe that this is happening since a change in TMDB that is now possible multiple translations for the same language across different regions (https://medium.com/tmdb-news/movie-tran ... .7hngob6c6). Probably have to update the TMDB plugin, can you please verify?

Sorry for my English.

http://forums.mediacentermaster.com/viewtopic.php?t=11549

**Comment by psouza4** [comment]
pt-BR language code support added to themoviedb.org fetcher.  Updates are now waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.15 build 20616.1399 (2.15.20616.1399).

**Comment by cldborges** [comment]
Thanks! How I download this version (2.15.20616.1399)?

**Comment by cldborges** [comment]
I turned on auto update and works, thanks.

**Comment by cldborges** [comment]
Doesn't work, the fetcher does not find any description or title in PT-BR, the message "The configured language (Português Brasileiro) isn't available for this title, so English will be used instead." appears.
