### ISSUE TITLE
Kodi nfo format for rating

### ISSUE THREAD

**Issue by hfunder** [psouza4/mediacentermaster#1753]
When scraping from nfo's generated by MCM the decimals of the ratings get dropped as they are formatted european style with a comma while Kodi requires it american stile with a period:

http://kodi.wiki/view/NFO_files/movies

I have not checked if this problem sneaks up in other places. http://kodi.wiki/view/NFO_files/tvshows

Might want to check the whole kodi nfo export format for inconsistencies

**Comment by psouza4** [comment]
Media Center Master uses the .NET framework to format numbers, which adheres to the rules of your regional settings in your Windows control panel.  Please check your Windows control panel to change the formatting to your liking.

**Comment by hfunder** [comment]
I do not agree with this: the nfo for tv shows are formatted correctly but not for movies so it does not seem that .NET has any influence. Anyway: Kodi expects to use the american system with "." and not the european with ","
