### ISSUE TITLE
Malware detected in kaspersky

### ISSUE THREAD

**Issue by Analogic2004** [psouza4/mediacentermaster#1755]
Detected object (process memory) deleted.	
c:\program files (x86)\media center master\mcmstublauncher.exe	
Process memory: c:\program files (x86)\media center master\mcmstublauncher.exe	
Object name: PDM:Trojan.Win32.Generic	
Object type: Other malware

**Comment by psouza4** [comment]
Definitely a false-positive if you downloaded this from our servers.
