### ISSUE TITLE
Commas in multi-episode xml file <EpisodeName> field

### ISSUE THREAD

**Issue by Darrin1** [psouza4/mediacentermaster#1760]
If a multi-episode iso has episode names with commas in them, the resulting kodi nfo file does not register the correct names.  For example, given the following xml entry:

<EpisodeName>Long Live the Queen, Toys in Babeland, Business, Italian Style, Double, Double, Toil and Trouble, Cheap, Cheap, No Zip in My Zap, Birdies, Bogies, and Baxter, Safe and Sane Halloween, Out of Sync, Out of Mind</EpisodeName>

Because of commas in episodes:

"Business, Italian Style", "Double, Double, Toil and Trouble", and etc. this field is not parsed correctly when creating the corresponding kodi nfo file. The result is that each title entry in the multi-episode kodi nfo file becomes the following:

<title>Long Live the Queen, Toys in Babeland, Business, Italian Style, Double, Double, Toil and Trouble, Cheap, Cheap, No Zip in My Zap, Birdies, Bogies, and Baxter, Safe and Sane Halloween, Out of Sync, Out of Mind</title>

Recommend either using a different delimiter (other than commas) in the xml file or just simply deleting commas from episode names prior to creating the <EpisodeName> field.

**Comment by psouza4** [comment]
For multi-episode files, the metadata will now replace commas with semicolons in the episode title and retain commas for delimiting them.  This should help Kodi and other media players that are specifically looking for commas to delimit the episode name when parsing local metadata.
