### ISSUE TITLE
MCM frozen because of hundreds of threads created

### ISSUE THREAD

**Issue by manuliege** [psouza4/mediacentermaster#1762]
I was busy with a rename of all my collection.
Then an auto check episodes started.
At first, there was no problem, the 2 operations were running together.
But at the end of the rename of a show, before beginning the rename of the next one, all suddenly was frozen (the rename, the auto check).
I looked in a process explorer and saw that the memory used by MCM was twice the max it's usually using.
And hundreds of threads were created.

**Comment by psouza4** [comment]
Please discuss support issues at the official support forums.  The Issue Tracker should only be used for reporting concise details of bug reports or feature requests that have previously been discussed at the support forums.  I can't really provide troubleshooting through the Issue Tracker.
