### ISSUE TITLE
Renaming Movies

### ISSUE THREAD

**Issue by mobuan** [psouza4/mediacentermaster#1764]
Could it be possible to add the audio channels to the movie folder like 5.1 or 7.1 or 2.0 ... 👍

**Comment by mobuan** [comment]
That would be a nice feature

**Comment by psouza4** [comment]
Media Center Master can already do this with the A:CH token, which works for both movies and T.V. episodes.

A:BR (bitrate), A:CH (channels), A:CO (codec), and A:FR (frequency) all describe audio tokens available to the renamer.

You can read more at the wiki:

http://wiki.mediacentermaster.com/index.php?title=Renaming_Tab_Settings#Audio_Quality
