### ISSUE TITLE
Does not leverage adult fetchers.

### ISSUE THREAD

**Issue by ChrisWeiss** [psouza4/mediacentermaster#1765]
MCM still seems to only utilize the primary/secondary movie fetchers, regardless of what is set for adult fetchers or what Mode is set. Even when doing Fetch/...As Adult (forced).

MCM v2.16

**Comment by psouza4** [comment]
I can't confirm this.

I added an adult title to just one of my regular movie folders and right-clicked it and told it to fetch...as adult and it used an adult fetcher, correctly tagging it with adult metadata and artwork.
