### ISSUE TITLE
Process New Downloads Does Not Tell Kodi To Update Library

### ISSUE THREAD

**Issue by dementiaLim** [psouza4/mediacentermaster#1768]
Thread acknowledgement here: http://forums.mediacentermaster.com/viewtopic.php?f=4&t=11825

When I run process new downloads, MCM does not seem to properly tell Kodi to scan for new content. I enabled debug, and the only post messages i see is a GUI.ShowNotification message, which to me seems like it would not actually tell Kodi to scan for new content, but just show users that new content is available.

When I run Tools > Run Kodi integration, I do see the post command "VideoLibrary.Scan" in the debug logs. This command is not present when I run process new downloads.

*Support Info:*
Installation name: Media Center Master
Installation date: 20140302
Media Center Master: 2.16.4517.861
Windows version: Windows 10 Pro (64-bit)
Windows version (raw): Microsoft Windows NT 6.2.9200.0
.NET framework information:
Runtime loaded: 2.0.50727.8745
Runtimes installed:
2.0.50727.4927 SP2
3.0.30729.4926 SP2
3.5.30729.4926 SP1
4.6.01586
4.0.0.0
AppData path: C:\Users\pvr\AppData\Roaming\Peter Souza IV\Media Center Master
AppSettingKey path: HKEY_CURRENT_USER\SOFTWARE\Peter Souza IV\Media Center Master
Command line: "C:\Program Files (x86)\Media Center Master\MCMStubLauncher.exe" /skipUAC
Current path: C:\Program Files (x86)\Media Center Master
Administrative details:
User is administrator: true
UAC status: enabled
Elevation status: elevated
Proxy:(none in use)

*Kodi version:*
17.1-RC1

*Settings:*
AllowSlowUIColumns: False
AnnouncementsLast: 1401473239
AppendParentalRatingsToMovieDescription: False
Art_AutoResize: True
Art_BackdropWidth: 1280
Art_EnableOldArtChooser: False
Art_PosterWidth: 320
Art_SeenNoPromptDisclaimer: True
Artwork_FanartTV: False
Artwork_FanartTV_ClearArt: True
Artwork_FanartTV_ClearArt_SaveAs: clearart
Artwork_FanartTV_ClearLogo: True
Artwork_FanartTV_DiscArt: True
Artwork_FanartTV_DiscArt_SaveAs: disc
Artwork_FanartTV_HD: True
Artwork_FanartTV_Logo_SaveAs: logo
Artwork_FanartTV_MovieBanner: True
Artwork_FanartTV_MovieBanner_SaveAs: banner
Artwork_FanartTV_Thumbnail: True
Artwork_FanartTV_Thumbnail_SaveAs: thumb
AskForIMDBIDOnUnknownMovies: True
AutoFetchMetaDataForTVScanFolders: True
AutoMaximizePosterWindow: False
AutoProcess_Fetch: True
AutoProcess_Move: True
AutoProcess_ParseAndIgnore: False
AutoProcess_Rename: True
AutoProcessNewTV: True
AutoRunNewMediaList: False
AutoShrinkPostersForDVDID: True
BestSummary: Use smallest available description
ConfirmationPromptTimeout: 30
CreateBlank: False
CreateDVDIDMetaData: False
CreateMovieNFOMetaData: True
CreatePyTiVoMetadata: False
DeepInspectVideoFor3D: False
DetectAndOrganizeSingleFileItems: True
DisableTorrenting: False
DontDownloadTVBefore: 7/12/2015 11:19:24 AM
DontFetchPictures: False
DontSaveWorkingCache: False
DontTryToElevateUAC: False
DotNetCheck_Status: Pass
Download_ParserInTestMode: False
DownloadAllBackdrops: True
DownloadCastThumbs: False
DownloadCrewThumbs: False
Downloader_AcceptArchives: True
Downloader_AgeThreshold: 4
Downloader_AllowAVI: True
Downloader_AllowFLV: False
Downloader_AllowMKV: True
Downloader_AllowMP4: True
Downloader_AllowMPG: True
Downloader_AllowWMV: False
Downloader_AvoidSubs: True
Downloader_Avoidx264: False
Downloader_CleanUp: True
Downloader_ExtractArchives: True
Downloader_InspectTrackers: True
Downloader_Movie_1080HD_SizeMax: 15000000000
Downloader_Movie_1080HD_SizeMin: 0
Downloader_Movie_720HD_SizeMax: 10000000000
Downloader_Movie_720HD_SizeMin: 0
Downloader_Movie_SD_SizeMax: 1500000000
Downloader_Movie_SD_SizeMin: 0
Downloader_MovieAllowForeign: False
Downloader_MovieExcludeTerms: cam r5 ts telesync webscr* dvdscr* scr dubbed german fr french dutch* swesub* vosfr nlsubs nl_subs dvd4 dvd5 dvd9
Downloader_MovieExcludeTerms_1080HD: 720*
Downloader_MovieExcludeTerms_720HD: 1080*
Downloader_MovieExcludeTerms_SD: 720* 1080*
Downloader_MovieIncludeTerms_1080HD: 1080*
Downloader_MovieIncludeTerms_720HD: 720*
Downloader_MovieQuality: 5
Downloader_ParserIgnoresReadOnly: True
Downloader_RatingThreshold: 4.5
Downloader_ReplaceUseBestQuality: False
Downloader_RunAtStartup: True
Downloader_Torrents_SkipPeerCheckOnNewUploads: True
Downloader_TV_1080HD_SizeMax: 8000000000
Downloader_TV_1080HD_SizeMin: 2000
Downloader_TV_720HD_SizeMax: 4000000000
Downloader_TV_720HD_SizeMin: 1000
Downloader_TV_SD_SizeMax: 1250000000
Downloader_TV_SD_SizeMin: 1000
Downloader_TVAllowForeign: False
Downloader_TVExcludeTerms: preair flv dubbed german fr french dutch* swesub* vosfr nlsubs nl_subs dvd4 dvd5 dvd9
Downloader_TVExcludeTerms_1080HD: 1080*
Downloader_TVExcludeTerms_720HD: 1080*
Downloader_TVExcludeTerms_SD: 720* 1080*
Downloader_TVIncludeTerms_1080HD: 720* x265*
Downloader_TVIncludeTerms_720HD: 720*
Downloader_TVQuality: 11
Downloader_UpgradeMovieQuality: False
Downloader_WantObscure: False
DownloadHistory_Filter: vander
DownloadHistory_Library: True
DownloadHistory_Movies: True
DownloadHistory_NotFound: True
DownloadHistory_Skip: True
DownloadHistory_Success: True
DownloadHistory_TV: True
DualPass: True
EpisodeRenamingConvention: N - SXXEYY - T
FilteringDisabled: True
FolderCleaner_AutoCleanOnFetch: True
FolderCleaner_DeleteSamples: True
FolderCleaner_DeleteStaleMetadata: True
FolderCleaner_DeleteUnknownFolders: True
FolderCleaner_DeleteUnknownImages: True
FolderCleaner_DeleteUnusedExternalMetadata: True
FolderCleaner_TestMode: False
ForcedTitleTag: True
HasSeenTooltipOnMinimize: True
HideTitleBarLicensing: False
HighlightMissingMeta: True
HTML_FastVideoInspection: True
IgnorePeriodFilesAndDirectories: True
ImagesByNameMode: New
Interval_AutoScan: 86400
Interval_AutoScanEpisodes: 86400
Interval_DownloadNewMovies: 86400
Interval_DownloadNewTV: 21600
Interval_DownloadParser: 1800
Interval_DownloadTorrentFeeds: 3600
Interval_NewMediaList: 7200
Interval_uTorrent: 900
LastFetchMode: 2
LicenseCache: SVAfg*******************
LicenseCode: MCMLT******************
LicenseDetails: {Privacy Censor}
LicensingMode: 2
LicensingSystemNew: True
LimitBackdropDownloads: 5
LogLimit: 500
LogTimestamp: False
LogToFile: True
ManualMovieConfirm: True
MaxFetcherThreads: 2
MCMInstallCheck: 1
MediaListSort: ListTitle_NoArticles/A
Metadata_AllowFetcherKeywordTags: True
Metadata_aTVFlash: False
Metadata_Boxee: False
Metadata_DLNA: False
Metadata_Embedded: False
Metadata_JRiver: False
Metadata_MediaBrowserOld: False
Metadata_MythTV: False
Metadata_WDTV: False
Metadata_XStreamer: False
MinimizeToTray: True
MoreRelaxedSearching: True
MoveMovieDownloadsTo: E:\My Videos\Movies
Movie_VotedScoreSource: primary fetcher
Netgear_AutoReduceFileSize: True
Netgear_CompatibleTextFields: False
Netgear_EmbedPoster: True
Netgear_Force_EASCII: True
Netgear_MetaData: False
Netgear_TLENID3Standard: True
NewMediaListDays: 7
NMTPathMapping: C:\Example\Path**file:///opt/sybhttpd/localhost.drives/NETWORK_SHARE/EXAMPLESHARE|
NoCommas: False
NoConfirmOnOneResult: True
NonblockingConfirmationPrompts: True
NoSpaces: False
NoSpaces2: False
OnlyShowAnnouncements: False
Plugin_Fetcher_Adult: TMDbA
Plugin_Fetcher_Movies1: tMDB
Plugin_Fetcher_Movies2: IMDB
Plugin_Fetcher_TV: thetvdb.com
PopupMoveWindow: False
PostProcessing_Hide: True
PostProcessing_Wait: True
PostProcessingTVEpisode_Hide: True
PostProcessingTVEpisode_Wait: True
PostProcessingTVShow_Hide: True
PostProcessingTVShow_Wait: True
ReadOnlyFoldersVisible: True
RelaxedTVDetection: True
RenameFiles: True
RenameFolders: True
Renamer_Movie: T T (Y)
Renamer_Series: T, T (Y)
RenamerDownloadStyle: False
RespectIDs: True
RuT_EnableManager: False
ScanFolders: E:\My Videos\TV Shows|E:\My Videos\Movies|I:\My Videos\TV Shows
SearchWithoutPath: False
SeasonRenamingConvention: Season {S}
ShowDebug: False
SortByOriginalFolder: False
SortWithoutArticle: True
Subtitle_NamingMode: Single
Subtitles_PreferedLanguage: in English
Subtitles_PreferedLanguages: en,en
ThemedBackgrounds: True
ThumbnailExtract_Auto: False
ThumbnailExtract_Lots: False
TMDb_CountryAbbreviation: US
TMDb_LanguageAbbreviation: en
TMDb_LanguageID: 7
TMDb_LanguageName: English
TorrentDownloadPath: C:\Users\pvr\Dropbox\Torrents
TorrentDownloadPathOther: C:\Users\pvr\Dropbox\Torrents
TorrentFinishedPath: I:\uTorrent\Done
Torrents_AllowMagnetLinks: True
Torrents_DisableVirusProtection: True
Torrents_DownloadDelay: 8
Torrents_MinimumEpisodeSeeds: 1
Torrents_MinimumMovieSeeds: 35
Trailers_AllowAdaptiveYouTubeTrailerMuxing: False
Trailers_AlwaysReEncode: False
Trailers_AutoDownload: False
Trailers_AutoReEncode: False
Trailers_AutoReplace: True
Trailers_MaxBitRate: 1600
Trailers_SaveLocation: 6
Trailers_TargetSize: 480 (pixels high)
Trailers_WatchOutput: False
Trakt: False
Trakt_Auto: False
Trakt_AutoAddTV: False
Trakt_AutoDownload: False
Trakt_AutoDownloadCheckRelease: True
Trakt_ReleaseDayOffset: 0
TranslateSEEtoAAA: False
TTVDB_LanguageAbbreviation: en
TTVDB_LanguageID: 7
TTVDB_LanguageName: English
TV_Overrides: dora the explorer*74697*|girls*220411*|law and order ci*71489*4203|law and order*72368*|mash*70994*4315|nexo knights*304433*|real housewives beverly hills*196741*|real housewives of new york city*84669*|real housewives of new york*84669*|real housewives of nyc*84669*|scandal us*248841*|scandal*248841*|some assembly required*279412*|tfh*71475*|the flash*279121*|the office us*73244*6061|the real housewives new york city*84669*|transformers*72499*|million dollar listing la*128521*
TVAutoScanCheckMissingThumbs: True
TVFetchSeasonBanners: True
TVFetchSeasonPosters: True
TVShowBias: US
TVThemeMusic: False
TVVideoBackdrops: False
UITheme: Windows Media Center
UpdateFile: Update.txt
UpdatePath: http://download.MediaCenterMaster.com/AutoUpdate/
UseAutoDetectionMode: False
UseAutoUpdate: True
UseCloudNetwork: True
UseConsolodatedGenres: False
UseExistingPosters: True
UseFetcherThreads: True
Usenet_AutoLoadNZB: False
Usenet_Binsearch: False
Usenet_CacheLocation: C:\Users\pvr\AppData\Roaming\Peter Souza IV\Media Center Master\Usenet
Usenet_MaxConnections: 20
Usenet_MCMIndex: False
Usenet_MoveNZBFile: False
Usenet_NZBsu: False
Usenet_Password: {Privacy Censor}
Usenet_Port: 119
Usenet_SSL: False
Usenet_UseMCMToDownload: True
UsePostProcessing: False
UsePostProcessingTVEpisode: False
UsePostProcessingTVShow: False
UseSecondaryGenres: True
UseWindowsProxy: True
UT_AutoForceTVDownloads: False
UT_AutoLabel: False
UT_AutoRemoveCompletes: True
UT_AutoRepair: True
UT_EnableManager: True
UT_Hostname: localhost
UT_LeaveSeedingTorrentsWithETA: False
UT_Password: {Privacy Censor}
UT_Port: 24932
UT_RemoteAddMagnets: True
UT_RemoteAddTorrents: True
UT_SeedUntilRatio: 0.000
UT_Username: {Privacy Censor}
VersionUpgrader: 5
WantExtendedTVStatus: False
WantMovieTorrentDownloader: False
WantNewMovieDownloads: False
WantOpenSubtitlesOrg: False
WantQueueAbortConfirmation: True
WantSmoothImages: False
WantSubtitleDownloads: False
WantSubtitleDownloads_Movies: False
WantSubtitleDownloads_TV: False
WantTorrent_eztv: True
WantTorrent_isohunt: True
WantTorrent_kickasstorrents: True
WantTorrent_newtorrents: True
WantTorrent_rarbg: True
WantTorrent_thepiratebay: True
WantTorrent_thepiratebay_new: True
WantTorrent_torrentbutler: True
WantTorrentAutoStart: True
WantTVTorrentDownloader: True
WantUsenet: False
WantVideoDetails: False
WhatToDoWithBadEpisodeDownloads: Re-download
XBMC_AlternatePosterSize: True
XBMC_API_Host: localhost
XBMC_API_Integration: True
XBMC_API_Notifications: True
XBMC_API_Password: {Privacy Censor}
XBMC_API_Port: 1979
XBMC_API_Scan: True
XBMC_API_Username: {Privacy Censor}
XBMC_ExtraFanart: True
XBMC_FillTitleFromOriginalTitle: False
XBMC_GenerateFanArtwork: True
XBMC_GeneratePosterArtwork: True
XBMC_NeverDeleteExtraFanart: True
XBMC_SpecialsSeasonHackFix: True
XBMC_Version: 12
YAMJEnabled: False

*Version Info:*
File versions (current + install path):
AutoUpdate.dll version: 2.29.114.881
MCMStubLauncher.exe version: 2.10.114.881
unins000.exe version: 51.52.0.0
File versions (%AppData%\bin):
AdultDVDEmpire.dll version: 3.20.32615.597
AutoUpdate.dll version: 2.30.34914.1417
cdUniverse.dll version: 3.5.214.914
ffmpeg.exe version: none
GayDVDEmpire.dll version: 3.20.32615.597
ICSharpCode.SharpZipLib.dll version: 0.86.0.518
IMDB.dll version: 3.27.17413.1304
Ionic.Zip.dll version: 1.9.1.8
MCMIDTag.dll version: 2.10.114.0
MCMMKVTag.dll version: 2.10.114.0
MCMWTV.dll version: 2.10.114.0
MediaCenterMaster.exe version: 2.16.4517.861
MediaInfo.dll version: 0.7.65.0
MonoTorrent.dll version: 0.80.0.0
Newtonsoft.Json.dll version: 5.0.5.16108
ObjectListView.dll version: 2.10.114.881
par2.exe version: none
RottenTomatoes.dll version: 1.2.19713.596
Sublight.Plugins.SubtitleProvider.dll version: 1.0.0.0
SublightPlugin.dll version: 2.13.34914.1417
System.Data.SQLite.dll version: 1.0.74.0
tMDB.dll version: 5.32.25415.922
TMDbA.dll version: 1.5.36113.600
unrar.dll version: 4.0.4.3
VidInfo.exe version: 2.15.25315.814

*Debug logs:*
-----------------------------------------------------------------------------------------
MCM: [F#-1] now working on Southern Charm (2014)
[22:01:21.758] DEBUG: Saved to cache: E:\My Videos\TV Shows\Southern Charm (2014)
thetvdb.com Updated base metadata for this show
[22:01:21.835] DEBUG: thetvdb.com Looking for artwork to download for this show
[22:01:21.878] DEBUG: thetvdb.com Finished looking for artwork to download for this show
[22:01:21.922] DEBUG: thetvdb.com Looking for episodes that need metadata fetched for this show
[22:01:21.987] DEBUG: thetvdb.com ... season list obtained (count = 1, now getting lists of episodes...
[22:01:22.069] DEBUG: thetvdb.com ...... looking for episodes in: Season 1
thetvdb.com Fetching season 1 banner...
thetvdb.com none available
[22:01:22.154] DEBUG: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\Southern Charm - S01E01 - Peter Pan “Sin”Drome.mp4 (file): true
[22:01:26.656] DEBUG: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\Southern Charm - S01E02 - Sh-Epic Fail!.mp4 (file): true
[22:01:26.677] DEBUG: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\Southern Charm - S01E02 - Sh-Epic Fail!.mp4
thetvdb.com Fetching data for season 1, episode 2
thetvdb.com "Sh-Epic Fail!"
[22:01:30.058] Fetching URL (POST): http://localhost:1979/jsonrpc
[22:01:30.059] DEBUG: Request data type switched to JSON
[22:01:30.061] Posted data: {"jsonrpc": "2.0", "method": "JSONRPC.Version", "id": "mcm"}
thetvdb.com Fetching season 1, episode 2 thumbnail...
[22:01:30.092] DEBUG: http://thetvdb.com/banners/episodes/278266/4814999.jpg
[22:01:30.092] DEBUG: Downloading: http://thetvdb.com/banners/episodes/278266/4814999.jpg
[22:01:30.093] DEBUG: ... to: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\metadata\4814999.jpg
[22:01:30.093] Fetching URL (GET): http://thetvdb.com/banners/episodes/278266/4814999.jpg
[22:01:30.110] Received data: {"id":"mcm","jsonrpc":"2.0","result":{"version":{"major":8,"minor":0,"patch":0}}}
[22:01:30.110] DEBUG: Version information from Kodi/XBMC: {"id":"mcm","jsonrpc":"2.0","result":{"version":{"major":8,"minor":0,"patch":0}}}
[22:01:30.139] Fetching URL (POST): http://localhost:1979/jsonrpc
[22:01:30.141] DEBUG: Request data type switched to JSON
[22:01:30.165] Posted data: {"jsonrpc": "2.0", "method": "GUI.ShowNotification", "params": {"title": "MCM: New Episode Fetched", "message": "Southern Charm - S01E02 - Sh-Epic Fail!", "displaytime": 8000}, "id": "mcm"}
[22:01:30.233] Received data: {"id":"mcm","jsonrpc":"2.0","result":"OK"}
[22:01:30.454] DEBUG: The image downloaded has a size of: 400x225
[22:01:30.520] DEBUG: Successfully wrote image data to disk.
[22:01:31.591] DEBUG: Operations ... completed community web conversation: 1,379ms
[22:01:32.911] DEBUG: Submitted details.
thetvdb.com Done with this show!
[22:01:33.123] DEBUG: Saved to cache: E:\My Videos\TV Shows\Southern Charm (2014)
[22:01:33.152] DEBUG: Saved to cache: I:\uTorrent
[22:01:35.354] DEBUG: Saved to cache: E:\My Videos\TV Shows\Southern Charm (2014)
[22:01:35.606] DEBUG: Saved to cache: E:\My Videos\TV Shows\Southern Charm (2014)
[22:01:40.202] DEBUG: Saved to cache: E:\My Videos\TV Shows\Southern Charm (2014)
MCM: Now resizing artwork for Southern Charm (2014)
[22:01:44.494] DEBUG: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\Southern Charm - S01E01 - Peter Pan “Sin”Drome.mp4 (file): true
[22:01:44.500] DEBUG: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\Southern Charm - S01E02 - Sh-Epic Fail!.mp4 (file): true
MCM: [F#210] Created Kodi/XBMC metadata files
MCM: Cleaning folder E:\My Videos\TV Shows\Southern Charm (2014)...
[22:01:44.939] DEBUG: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\Southern Charm - S01E01 - Peter Pan “Sin”Drome.mp4 (file): true
[22:01:48.090] DEBUG: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\Southern Charm - S01E02 - Sh-Epic Fail!.mp4 (file): true
[22:01:48.264] DEBUG: Saved to cache: E:\My Videos\TV Shows\Southern Charm (2014)
MCM: ... 0 files deleted
[22:01:48.729] DEBUG: E:\My Videos\TV Shows\Southern Charm (2014)\Season 1\Southern Charm - S01E01 - Peter Pan “Sin”Drome.mp4 (file): true
MCM: ...done!

**Comment by psouza4** [comment]
Code missing for episodes fetched via Download Parser (but not by movies).  Extended missing functionality to episodes and will implement changes via next autoupdate version.

**Comment by dementiaLim** [comment]
Hi,
This still seems broken. It was able to successfully update one new episode, but the next day, two more episodes downloaded by uTorrent, was parsed by media center master, but did not trigger an update to Kodi.  I had to manually run the "Tell Kodi to update now" in order for Kodi to see the two new episodes that were downloaded.

**Comment by psouza4** [comment]
Additional debug is being added to the next version.  I don't see an issue here, personally.  The extra debug is available by enabling developer-level debug from the Help menu and will be available in the next auto-update.  It should be very verbose and will help us track down what's going on, but a new log from you will definitely be necessary.
