### ISSUE TITLE
Emby requires short MPAA/content rating in NFO metadata

### ISSUE THREAD

**Issue by Happy2Play** [psouza4/mediacentermaster#1777]
There is no field in the nfo file that covers contentrating from the xml.

**Comment by psouza4** [comment]
There's a certification and mpaa field that contains the content rating in NFO exports.

**Comment by Happy2Play** [comment]
Sorry I guess Emby does read the mpaa rating but since MCM list "Rated PG-13 for violence, action and scary images, and for some suggestive content and partial nudity" it jacks up Parental controls.

**Comment by psouza4** [comment]
Emby should be reading the movie.xml metadata as it has for the last decade (since back when it was MediaBrowser).  Are your Emby metadata settings correct?

**Comment by Happy2Play** [comment]
Well they can only read xml's now via a plugin, so you are unable to make any updates via Emby if you are using xml metadata.  .

I still use xml via Emby, but there are reports on Emby forum of issues of MCM created nfo files.

**Comment by psouza4** [comment]
Some cited sources would be great... links to specific issues posted as separate issues here at the Github issue tracker as well as details on what XML tags Emby wants in NFO files.

**Comment by Happy2Play** [comment]
Well currently at least in the beta cycle all xml metadata and images are broken from there.

I will pm Luke to see what I can get.

**Comment by Happy2Play** [comment]
As for this issue it would be all the additional info in mpaa.

Here are examples Luke provided.

[tvshow.zip](https://github.com/psouza4/mediacentermaster/files/1286084/tvshow.zip)
[127 Hours (2010).zip](https://github.com/psouza4/mediacentermaster/files/1286085/127.Hours.2010.zip)


But yes this does come down to how you have Emby configured.  And Luke prefer everyone use there providers and nfo format as dev you now how to troubleshoot info you provide.

**Comment by psouza4** [comment]
So basically Emby wants the short content rating for movies instead of the full content rating.  Okay.

I've added a new option in Settings & Preferences that will let you export the short content rating to the mpaa field in NFO files.  This breaks compatibility with Kodi though so you can either use your NFO files with one or the other (unless you don't care about longer content ratings in Kodi).

![image](https://user-images.githubusercontent.com/2042341/30393654-12a8e500-987e-11e7-8c75-234a8826b243.png)

**Comment by psouza4** [comment]
Feature added and waiting for next release.

**Comment by psouza4** [comment]
Released update in version 2.17.26917.859.
