### ISSUE TITLE
Please sort Status Column by date, not alphabetically

### ISSUE THREAD

**Issue by muzicman61** [psouza4/mediacentermaster#1778]
Sorting of the status column sorts alphabetically and not chronologically.

Example:

Nova:                               Next Episode 9/13/2017
Strain, The:                       Next Episode 9/3/2017
American Horror Story:    Next Episode 9/5/2017

As you can see it is not chronological.  When it is a short list like above it is not that big a deal but when you have dozens of shows it becomes difficult to see what's what.

Thanks.

**Comment by psouza4** [comment]
Not all of the data in this column represents a date, so a simple date-parsing comparitor won't do the trick to sort this column by date.  I'll consider alternatives, such as how the date is formatted so that a basic. alpha sort would work.

**Comment by psouza4** [comment]
A new option has been added to format this column in a date-sortable way.

Feature added and waiting for next release.

**Comment by muzicman61** [comment]
Thanks! Great job!!!

**Comment by psouza4** [comment]
Released update in version 2.17.26917.859.
