### ISSUE TITLE
IMDb 'ReleaseDate' (theatrical release) movie.xml metadata field needs reformatting

### ISSUE THREAD

**Issue by Happy2Play** [psouza4/mediacentermaster#1784]
If you have IMDB then TMDB the layout is 

mm/dd/yyyy

But if you have TMDB then IMDB you get

yyyy/mm/dd

Just notice this as Emby was not reading some Premiere Dates when processed by a test machine.

**Comment by psouza4** [comment]
I'm not sure what you mean by 'date layout' -- are you talking about what date is saved to metadata?  That date is always region-formatted according to your configured Windows OS settings.  In Windows control panel go to Region -> Formats -> Short date.

**Comment by Happy2Play** [comment]
Specific Example 	
<PremiereDate>12/17/1982</PremiereDate> Imdb then tmdb
<PremiereDate>1982-12-03</PremiereDate> tmdb then imdb

**Comment by psouza4** [comment]
... are we talking about what's saved into metadata?  If so, which file?

Examples from logs?  Example metadata files? 

I need _something_ to work with.

**Comment by Happy2Play** [comment]
Here are example showing date format differences, with only changing fetcher order.

[movie-imdb-tmdb.txt](https://github.com/psouza4/mediacentermaster/files/1337593/movie-imdb-tmdb.txt)
[movie-tmdb-imdb.txt](https://github.com/psouza4/mediacentermaster/files/1337594/movie-tmdb-imdb.txt)

**Comment by Happy2Play** [comment]
Emby wants yyyy-mm-dd, so that would be the preferred format (at least for me).

**Comment by psouza4** [comment]
You are specifically talking about just the theatrical release date of the movie in the movie.xml metadata file as it's provided by the IMDb fetcher.  That's what the info I needed and was able to figure out from your attachments.  I've updated the issue accordingly and will accept it into the tracker.

**Comment by psouza4** [comment]
Fixed in IMDb fetcher version 3.8 (build 4418.784).

It will be included in the next update to Media Center Master.

**Comment by psouza4** [comment]
Released in version 2.18 build 4518.858 (2.18.4518.858).
