### ISSUE TITLE
Append Parental Guide Summary To Description

### ISSUE THREAD

**Issue by bling26** [psouza4/mediacentermaster#1785]
Shortly after August 17th 2017 the Parental Guide stopped working like it has for all the years I have used this software. I have always had it set to use IMDB and download the shortest description with parental rating summary. It worked before August 17th but not after. I still get the short description however the parental part has zeros for all categories. I checked IMDB and it seems they might have changed their rating scheme from a number system to "mild, moderate, etc" system. I do not feel like it is an issue with MCM rather the fetcher is looking for data that does not exist any longer since the provider (IMDB) changed their structure.

For example I used to get results like the following:

Parental Rating Summary:
MPAA Rating: R
Sex &amp; Nudity: 3
Violence &amp; Gore: 4
Profanity: A great deal of profanity throughout the movie.
Alcohol/Drugs/Smoking: 1
Frightening/Intense Scenes: 0

...but now I get:

Parental Rating Summary:
MPAA Rating: R
Sex &amp; Nudity: 0
Violence &amp; Gore: 0
Profanity: none
Alcohol/Drugs/Smoking: 0
Frightening/Intense Scenes: 0

This is not a huge deal but it is nice to see that on my front end so I know what to expect. I'm sure I did not provide you with enough information but I will if needed. Thanks for your help.

**Comment by vvicked** [comment]
I am also noticing that i don't get the actual move summary any more.  Only the empty parental ratings

**Comment by Happy2Play** [comment]
>@vvicked I am also noticing that i don't get the actual move summary any more. Only the empty parental  @ratings

Why report here and not forum?  This is totally different issue.  I haven't seen this issues, so what is your Movie description set to?
Application-S&P-Movies

**Comment by vvicked** [comment]
I apologize, I did check the forum and saw that someone reported issues with the Parental guide summary on the forum and submitted the issue ticket before me.  The other issue related to Parental guide I believe is related to the movie descriptions moving to plot/synopsis tags while the parental guide is still appended to (empty) overview/description, which is used by emby.

Just let me know if you prefer me to create a new forum topic for this as a separate issue.

**Comment by bling26** [comment]
I created this threat a while ago and it has not yet been addressed. I think the parental rating option is low priority and not used by most users. All other synopsis items seem to be working. I looked at IMDB and they clearly changed their format from a number scheme to a "Moderate/Sever/etc" scheme. Kind of dumb.

**Comment by vvicked** [comment]
Bummer, it's the most used feature in my house.  It's probably because I was the original requester of the feature :)

**Comment by psouza4** [comment]
Fixed and waiting next release.

**Comment by psouza4** [comment]
Released in version 2.18.1818.1010.

**Comment by bling26** [comment]
Works like a charm, thank you. Keep up the good work!
