### ISSUE TITLE
9-1-1 Can't find valid downloads

### ISSUE THREAD

**Issue by HnyBear** [psouza4/mediacentermaster#1787]
http://forums.mediacentermaster.com/viewtopic.php?f=4&t=12094&p=48632#p48632

**Comment by psouza4** [comment]
Please use the relaxed search option for this show to download episodes.

**Comment by Happy2Play** [comment]
Weird result in my test downloading 9-1-1 with relaxed search
![test](https://user-images.githubusercontent.com/10268557/35128880-8d60c666-fc6d-11e7-8ce9-d7771ab4ad91.jpg)

**Comment by HnyBear** [comment]
Although that was working, it's not working anymore.

**Comment by psouza4** [comment]
The comparer does seem to be broken in this case.  Working on a fix.

**Comment by psouza4** [comment]
Fixed and waiting for next release.

**Comment by psouza4** [comment]
Release in version 2.18 build 2218.1196 (2.18.2218.1196).
