### ISSUE TITLE
Invalid response from RARBG

### ISSUE THREAD

**Issue by markt9** [psouza4/mediacentermaster#1817]
As discussed in the forums: 

[07:21:18.270] Fetching URL (GET): https://torrentapi.org/pubapi_v2.php?ge ... =get_token
RARBG.to: Invalid response from RARBG: 
MCM: RARBG API is not responding or returning errors!

If I try https://torrentapi.org/pubapi_v2.php?ge ... =get_token from my browser, I get "Invalid API parameters!"

**Comment by markt9** [comment]
I think I might have something.  The API now requires app_id on the get_token request!

https://torrentapi.org/pubapi_v2.php?app_id=Jackett&get_token=get_token works but https://torrentapi.org/pubapi_v2.php?get_token=get_token does not

**Comment by markt9** [comment]
https://torrentapi.org/apidocs_v2.txt first line says "When querying the api please use the app_id parameter with your app name so we can generate statistics for it."

**Comment by psouza4** [comment]
Thanks for your comments, everyone.  I do get notifications for everything posted here, so I don't need to be PMed, too.  I'm in the process of updating Media Center Master to the API changes.

**Comment by tobeychris** [comment]
Thanks Pete!

**Comment by psouza4** [comment]
Torrent source updated and waiting for next release.

**Comment by psouza4** [comment]
Released in version 2.18 build 9618.773 (2.18.9618.773).
