### ISSUE TITLE
AdultDVDEmpire scraper front cover image (poster) no longer downloading

### ISSUE THREAD

**Issue by WoodysMods** [psouza4/mediacentermaster#1820]
AdultDVDEmpire scraper front cover image (poster) no longer downloading, also doesn't list actors. Source change?

**Comment by WoodysMods** [comment]
AdultDVDEmpire no longer works at all.

**Comment by psouza4** [comment]
Source fixed; waiting for next MCM release.

**Comment by psouza4** [comment]
Released in version 2.19.21019.821.
