### ISSUE TITLE
Possible Metacritic HTML change 

### ISSUE THREAD

**Issue by Happy2Play** [psouza4/mediacentermaster#1833]
Warning: website isn't showing us a list of new movies

5:30 PM :: metacritic.com:  Looking for new movie releases...
5:30 PM :: [17:30:03.157] Fetching URL (GET):  http://www.metacritic.com/browse/dvds/release-date/new-releases/date?view=detailed
5:30 PM :: MCM:  Warning:  website isn't showing us a list of new movie releases -- did the HTML change?
5:30 PM :: MCM:  All new release movies have been downloaded.

http://forums.mediacentermaster.com/viewtopic.php?f=4&t=12733

**Comment by sociableWeaver** [comment]
Ditto issue.

**Comment by psouza4** [comment]
Fixed in version 2.18.32818.738.
