### ISSUE TITLE
TheTVDB.com URL has changed to TheMovieDB.org

### ISSUE THREAD

**Issue by ghost** [psouza4/mediacentermaster#1837]
This morning, I was trying to add The 100 to my list of TV shows and I wasn't able to get MCM to resolve the show using the name (it detected some National Geographic show, and some other one called 100%) or the TVDB code.  It appears that the address for the TVDB has changed to TheMovieDB.  I think this may be throwing off the URL resolver to go and scrape the information.

**Comment by Happy2Play** [comment]
This is normal.

thetvdb.com  now working on The 100
thetvdb.com  Potential match #272209 - "100%", 85% match
thetvdb.com  Potential match #80794 - "100%", 85% match
thetvdb.com  Unable to determine what show this is

MCM does not resolve the show in the initial query and you have to enter thetvdb id "268592".  
Not sure what you mean by " It appears that the address for the TVDB has changed to TheMovieDB".

**Comment by ghost** [comment]
I thought maybe the link in use was the problem.  When you try to visit
thetvdb.com in a browser it resolves to themoviedb.com, not thetvdb.com.

In any case, thanks.  I will try that ID.

**Comment by Happy2Play** [comment]
Sorry but I have no issue getting to thetvdb.com.  So it would have to be a issue on your side if your are redirected to tmdb.

**Comment by ghost** [comment]
Huh.  Alright.  Thanks.

**Comment by ghost** [comment]
After having tried the id you suggested (and I was able to load the website), MCM still doesn't download the metadata.  It shows with a yellow highlight.
