### ISSUE TITLE
Trailers won't download

### ISSUE THREAD

**Issue by Happy2Play** [psouza4/mediacentermaster#1841]
Trailers have stopped downloading recently.  

>1:14 PM :: [13:14:52.686] Fetching URL (GET):  http://www.youtube.com/get_video_info?video_id=Y_JGZTlUbZg&asv=3&el=detailpage&hl=en_US
1:14 PM :: YouTube:  The YouTube link for "Captain Marvel" (2019) is not valid
1:14 PM :: YouTube:  ... http://www.youtube.com/watch?v=Y_JGZTlUbZg||MCM||URL||MCM||http://www.youtube.com/watch?v=Y_JGZTlUbZg 
1:14 PM :: [13:14:52.795] Fetching URL (GET):  http://trailers.apple.com/trailers/home/scripts/quickfind.php?callback=searchCallback&q=captain+marvel
1:14 PM :: [13:14:52.826] DEBUG:  Video is HEVC: False
1:14 PM :: [13:14:52.826] DEBUG:  Video bitrate: 7095000
1:14 PM :: [13:14:52.842] DEBUG:  Saved to cache: Z:\ServerFolders\Videos\Movies\Captain Marvel (2019)
1:14 PM :: [13:14:53.545] DEBUG:  Result: Captain Marvel (2019)
1:14 PM :: [13:14:53.545] DEBUG:  ... is really close match!
1:14 PM :: [13:14:53.545] DEBUG:  ... is year match!
1:14 PM :: iTunes Trailers:  match! ("Captain Marvel (2019)")
1:14 PM :: [13:14:53.545] Fetching URL (GET):  http://trailers.apple.com/trailers/marvel/captain-marvel/
1:14 PM :: [13:14:53.576] DEBUG:  Video is HEVC: False
1:14 PM :: [13:14:53.576] DEBUG:  Video bitrate: 7095000
1:14 PM :: [13:14:53.608] DEBUG:  Saved to cache: Z:\ServerFolders\Videos\Movies\Captain Marvel (2019)
1:14 PM :: [13:14:53.748] Fetching URL (GET):  https://trailers.apple.com/trailers/feeds/data/20376.json
1:14 PM :: iTunes Trailers:  Looking for best quality version of this trailer at Apple's website...
1:14 PM :: iTunes Trailers:  ... 1080p is available
1:14 PM :: [13:14:53.795] DEBUG:  Apple trailer URL: https://movietrailers.apple.com/movies/marvel/captain-marvel/captain-marvel-trailer-2_1080p.mov
1:14 PM :: [13:14:53.795] DEBUG:  Size of DL is: 1 B (1)
1:14 PM :: [13:14:54.029] DEBUG:  Adjusted trailer URL: http://movietrailers.apple.com/movies/marvel/captain-marvel/captain-marvel-trailer-2_h1080p.mov
1:14 PM :: iTunes Trailers:  no suitable trailer download found

When you click the YouTube trailer url you get redirected to https and the trailer plays.

http://forums.mediacentermaster.com/viewtopic.php?f=4&t=19513

**Comment by psouza4** [comment]
Looks like YouTube is requiring https now.  Fixed in my dev version and will push an update soon.

**Comment by psouza4** [comment]
Fixed the Apple trailers issue too.  New update is live build 15319.933.
