### ISSUE TITLE
Thetvdb.com Api down or api change and TV state with sortable list is broken

### ISSUE THREAD

**Issue by Totto16** [psouza4/mediacentermaster#1846]
Thetvdb.com the api always responds " Fetching data for season 8, episode 15
[22:29:23.986] Fetching URL (GET):  [exception: Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig.]/api/767CE15749DAFFA2/series/72108/default/8/15/de.xml"

And TV state with sortable list is broken, only shows upcoming and not next episode - 01.08.2019
Or On Break, please fix the second cause its the best feature in the list.

**Comment by psouza4** [comment]
Hello, @Totto16 ,

Thanks for your bug report -- please make sure you follow all the relevant rules for posting bugs.

Your first issue is already being discussed here:
http://forums.mediacentermaster.com/viewtopic.php?f=4&t=19620&p=60043#p60043

And second issue is here:
http://forums.mediacentermaster.com/viewtopic.php?f=6&t=19618

Bugs should not be posted together, but instead separately and you should ensure they're not already in active discussion first.

Thanks!

**Comment by Totto16** [comment]
But i didn't watch into the forum nad here it wasn't mentionend, sorry, and the 2 Problem isn't mentioned in the 2 forum post, but i think it will resolve with the first, cause it doesnt recieves Airing dates anymore...

**Comment by psouza4** [comment]
It's okay, no worries.

The rules for posting bug reports and requesting support also appear here:

https://github.com/psouza4/mediacentermaster

And here:

http://www.mediacentermaster.com/support/

It is to help me since I am a solo developer.

Thetvdb.com will be repaired soon (hours)!
