### ISSUE TITLE
Thetvdb Fetching Series with more than one network

### ISSUE THREAD

**Issue by Totto16** [psouza4/mediacentermaster#1857]
If you're fetching A series like https://www.thetvdb.com/series/la-casa-de-papel with 2 or more networks it feches only the data from the first network for all seasons, in example it doesn't recognize that there are 3 seasons on netflix, it only says, 3. season not found for the first network Antena 3, is it possible with the new API v3 to iterate through these Networks and let the user decide wich one's the right?

**Comment by psouza4** [comment]
Sorry, at this time, thetvdb.com only returns the original network that airs the show:

```
 {
  "data": {
    "id": 327417,
    "seriesName": "Money Heist",
    "aliases": [
      "La casa de papel"
    ],
    "banner": "graphical/5d3601adceba4.jpg",
    "seriesId": "",
    "status": "Continuing",
    "firstAired": "2017-05-02",
    "network": "Netflix",
    "networkId": "",
    "runtime": "45",
    "genre": [
      "Thriller"
    ],
    "overview": "A master stroke devised and perfected for years, planned for months and executed in a few minutes so that the chosen group of thieves who enters the National Mint and Timbre at gunpoint make the police believe that their plan has failed... And that they are besieged inside the building with no other exit than their surrender.",
    "lastUpdated": 1563820461,
    "airsDayOfWeek": "Friday",
    "airsTime": "3:00 AM",
    "rating": "TV-MA",
    "imdbId": "tt6468322",
    "zap2itId": "",
    "added": "2017-04-21 16:27:27",
    "addedBy": 472274,
    "siteRating": 9.2,
    "siteRatingCount": 46,
    "slug": "la-casa-de-papel"
  }
}
```

This is from v3 of their API that I just tested with.  Additionally, their API lists 'network' and 'networkId' as strings and not arrays: https://api.thetvdb.com/swagger#!/Series/get_series_id

**Comment by Totto16** [comment]
Ok, than it's an error on there side, but can the api do something with those 2 URLs: https://www.thetvdb.com/series/la-casa-de-papel/allseasons/official
https://www.thetvdb.com/series/la-casa-de-papel/allseasons/alternate

**Comment by psouza4** [comment]
> Ok, than it's an error on there side, but can the api do something with those 2 URLs: https://www.thetvdb.com/series/la-casa-de-papel/allseasons/official
> https://www.thetvdb.com/series/la-casa-de-papel/allseasons/alternate

What do you need it to do with those URLs?  (also, you may need to wait for thetvdb.com to come back online since they're performing a data rollback to API v2 https://forums.thetvdb.com/viewtopic.php?f=118&t=57711 )

**Comment by Happy2Play** [comment]
You can manually add the additional network via the UI/Metadata tab.
example but it is still a matter of other programs actually displaying them.
<Network>Fox|Netflix</Network>

But ultimately the provider sets the limitations.

Wouldn't the "Alternate" fall under the same as DVD or Absolute Number?
