### ISSUE TITLE
When i FORCE a thetvdb season, it get the wrong id number

### ISSUE THREAD

**Issue by Kedryn** [psouza4/mediacentermaster#1858]
Sometimes i need to force a show by it's thetvdb id number.
When i paste the id, MCM will get the wrong id. I don't have a real example here now, i'll update as soon i have, but, for getting an idea, if i past a number like 245145 in the textbox, then MCM often don't scrape that serie, but another one with anothe id.

**Comment by psouza4** [comment]
Is there a discussion about this posted at the community forums?

All bug reports need to be verified with logs and your support information.  These rules are posted here at the Issue Tracker and at the forums.  I can't substantiate bug reports without going through the necessary steps.
