### ISSUE TITLE
Data and images missing from thetvdb

### ISSUE THREAD

**Issue by Kedryn** [psouza4/mediacentermaster#1859]
We all know what thetvdb has done in last few days, but they are stating that they did a full rollback to v2 of their site

I downloaded latest update of MCM few moments ago, but there are stil errors fetching shows data.

20.26 :: MCM:  [F#1] now working on Tejina Senpai
20.26 ::  tv  db   Updated base metadata for this show
20.26 ::  tv  db   Fetching show banner...
20.26 ::  tv  db   	none available
20.26 ::  tv  db   Fetching season 1 poster...
20.26 ::  tv  db   	none available
20.26 ::  tv  db   Done with this show!
20.26 :: fanart.tv:  Looking for clear art for Tejina Senpai...
20.26 :: fanart.tv:  ... none found
20.26 :: fanart.tv:  Looking for clear logo for Tejina Senpai...
20.26 :: fanart.tv:  ... none found
20.26 :: fanart.tv:  Looking for thumbnail artwork for Tejina Senpai...
20.26 :: fanart.tv:  ... none found
20.26 :: fanart.tv:  Looking for thumbnail artwork for Tejina Senpai, season 1...
20.26 :: fanart.tv:  ... none found
20.26 :: MCM:  Renaming ToaruKagakuNoAccelerator_Ep_04_SUB_ITA.mp4 to - S01E04 - (un-fetched episode).mp4
20.26 :: MCM:  ... metadata missing for this episode (fetching)
20.26 ::  tv  db   Now working on G:\Il mio Drive\media\anime\Toaru Kagaku no Accelerator
20.26 ::  tv  db   Updated base metadata for this show
20.26 ::  tv  db   Fetching show banner...
20.26 ::  tv  db   	none available
20.26 ::  tv  db   Fetching data for season 1, episode 4
20.26 ::  tv  db   ""
20.26 ::  tv  db   Fetching season 1, episode 4 thumbnail...
20.26 ::  tv  db   	error downloading: https://artworks.thetvdb.com/banners/episodes/360438/7231706.jpg
20.26 ::  tv  db   Done with this episode!

I dont know if this is still a problem of the thetvdb , a problem of Peter trying to catch up with thetvdb disaster.
Anyway, right now, most of the times i get that error

**Comment by psouza4** [comment]
Check my Facebook or Twitter for the current status on this (updated late last night). 👍

**Comment by Happy2Play** [comment]
You have to wait on TVDB to resolve their issue.  It can take days to weeks for TVDB to have all their data/images available again.

http://platypus.thetvdb.com/series/tejina-senpai/seasons/official/1  (looks like google took me to their beta site)

Their rollback appears to be working.
https://www.thetvdb.com/series/tejina-senpai/episodes/7254085
