### ISSUE TITLE
Thetvdb Issue in thumbnail fetching

### ISSUE THREAD

**Issue by Totto16** [psouza4/mediacentermaster#1868]
For some Api calls when it tries to download an thumbnail for an episode it calls 
https://artworks.thetvdb.com/banners/episodes/... and not  tv  db   	https://thetvdb.com/banners/episodes/... per example : "https://artworks.thetvdb.com/banners/episodes/368387/7327835.jpg" Gives an error and "https://www.thetvdb.com/banners/episodes/368387/7327835.jpg" not, its msterios.

**Comment by Happy2Play** [comment]
There are two different api plugins for TVDB v3 and v2.  And TVDB rolled back their v3 update so you need to change to the v2 plugin.

But yes it would appear that MCM may need to drop "artworks" from the url in v3 plugin.

**Comment by Totto16** [comment]
ANd how do you do that?

**Comment by Happy2Play** [comment]
> ANd how do you do that?

Application-Manage fetchers and plugins
