### ISSUE TITLE
The remote name could not be resolved: 'cf2.imgobject.com'

### ISSUE THREAD

**Issue by Happy2Play** [psouza4/mediacentermaster#1870]
TMDB is throwing Exception: System.Net.WebException for all Cast and crew images.
[Activity log for 2019-10-08.log](https://github.com/psouza4/mediacentermaster/files/3703702/Activity.log.for.2019-10-08.log)

http://forums.mediacentermaster.com/viewtopic.php?f=4&t=19677&p=60336#p60336

**Comment by Happy2Play** [comment]
Updated topic, today this Cast and Crew are working.  So I would assume this was something on TMDBs end.  Will continue to monitor.

**Comment by psouza4** [comment]
Yeah sounds like their CDN was down.  DNS unresolvable wouldn't be something I can fix usually. :)

**Comment by Happy2Play** [comment]
This is happening again.
http://forums.mediacentermaster.com/viewtopic.php?f=6&t=20296
http://forums.mediacentermaster.com/viewtopic.php?f=4&t=20315
