### ISSUE TITLE
Fetching no episode title

### ISSUE THREAD

**Issue by Kedryn** [psouza4/mediacentermaster#1871]
I have some shows that are fetched wrongly. For examample "Harrow" is fetched as empty episode names. Plex fetches from the same place, but without problems. (I'm fetching italian names)

21.42 :: MCM:  [F#3] now working on Harrow
21.42 ::  tv  db   now working on Harrow
21.42 ::  tv  db   Potential match #342568 - "Harrow", 100% match
21.43 ::  tv  db   Updated base metadata for this show
21.43 ::  tv  db   Fetching season 1 poster...
21.43 ::  tv  db   	none available
21.43 ::  tv  db   Fetching data for season 1, episode 1
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 2
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 3
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 4
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 5
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 6
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 7
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 8
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 9
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 1, episode 10
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 1
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 2
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 3
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 4
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 5
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 6
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 7
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 8
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 9
21.43 ::  tv  db   ""
21.43 ::  tv  db   Fetching data for season 2, episode 10
21.43 ::  tv  db   ""
21.43 ::  tv  db   Done with this show!

**Comment by Happy2Play** [comment]
And does it work properly with TVDB v2 fetcher?  Log clearly show the TVDB v3 fetcher is being used.  There are dozens of topic about how TVDB messed everything up trying to put v3.

**Comment by Kedryn** [comment]
![image](https://user-images.githubusercontent.com/12759632/67086402-ee80f180-f1a0-11e9-828e-683d0e603804.png)
I'm not using V3

**Comment by Happy2Play** [comment]
But the log snippet is showing tv.db which is tvdb v3 fetcher.  v2 would show thetvdb.com.  Log and support information will be needed.  As this would only appear to be a issue for you.

But this should be in the forum and not on github.

Also is your fetcher set at Series level? Series-Metadata

**Comment by Happy2Play** [comment]
But I just tested both v2 and v3 on your example above and both work but clearly a v3 issue.  But will try to see if language makes a difference.

v3

> MCM:  [F#2] now working on Harrow
 tv  db   now working on Harrow
 tv  db   Potential match #342568 - "Harrow", 100% match
 tv  db   Updated base metadata for this show
 tv  db   Fetching show poster...
 tv  db   Downloading and saving up to 6 backdrops...
 tv  db    ... backdrop #1
 tv  db    ... backdrop #2
 tv  db    ... backdrop #3
 tv  db    ... backdrop #4
 tv  db    ... backdrop #5
 tv  db    ... backdrop #6
 tv  db    ... 6 backdrops were saved
 tv  db   Fetching show banner...
 tv  db   Fetching season 1 poster...
 tv  db   Fetching data for season 1, episode 1
 tv  db   "Actus Reus"
 tv  db   Fetching season 1, episode 1 thumbnail...
 tv  db   Fetching data for season 1, episode 2
 tv  db   "Ex Animo"
 tv  db   Fetching season 1, episode 2 thumbnail...
 tv  db   Done with this show!
fanart.tv:  Looking for clear art for Harrow...
fanart.tv:  ... saved (HD)
fanart.tv:  Looking for clear logo for Harrow...
fanart.tv:  ... saved (HD)
fanart.tv:  Looking for thumbnail artwork for Harrow...
fanart.tv:  ... saved
fanart.tv:  Looking for thumbnail artwork for Harrow, season 1...
fanart.tv:  ... none found
MCM:  [F#2] Created Kodi/XBMC metadata files

v2

> MCM:  [F#3] now working on Harrow
thetvdb.com  now working on Harrow
thetvdb.com  Updated base metadata for this show
thetvdb.com  Fetching show poster...
thetvdb.com  Downloading and saving up to 6 backdrops...
thetvdb.com   ... backdrop #1
thetvdb.com   ... backdrop #2
thetvdb.com   ... backdrop #3
thetvdb.com   ... backdrop #4
thetvdb.com   ... backdrop #5
thetvdb.com   ... backdrop #6
thetvdb.com   ... 6 backdrops were saved
thetvdb.com  Fetching show banner...
thetvdb.com  Fetching season 1 poster...
thetvdb.com  Fetching season 1 banner...
thetvdb.com  	none available
thetvdb.com  Fetching data for season 1, episode 1
thetvdb.com  "Actus Reus"
thetvdb.com  Fetching season 1, episode 1 thumbnail...
thetvdb.com  Fetching data for season 1, episode 2
thetvdb.com  "Ex Animo"
thetvdb.com  Fetching season 1, episode 2 thumbnail...
thetvdb.com  Done with this show!
fanart.tv:  Looking for clear art for Harrow...
fanart.tv:  ... saved (HD)
fanart.tv:  Looking for clear logo for Harrow...
fanart.tv:  ... saved (HD)
fanart.tv:  Looking for thumbnail artwork for Harrow...
fanart.tv:  ... saved
fanart.tv:  Looking for thumbnail artwork for Harrow, season 1...
fanart.tv:  ... none found
MCM:  [F#3] Created Kodi/XBMC metadata files

https://forums.thetvdb.com/viewtopic.php?f=122&t=59455&sid=0294c18a7dfdab63179bdb277c4ef144

**Comment by Happy2Play** [comment]
Well the Series is translated to Italian but Season and Episode are not.  But it still processes for me.

Italian Series description with English episode descriptions.

**Comment by Kedryn** [comment]
I've found that with many tv shows, i have to juggle between V3 or V2 API, else the renaming of episodes gives no show nor episode titles in the filename. Some shows works anyway, some needs V2 and some V3.

**Comment by Happy2Play** [comment]
Not a whole lot can be done until TVDB stabilizes.
