### ISSUE TITLE
"Daily" Shows not processing since thetvdb changes

### ISSUE THREAD

**Issue by MojoGitly** [psouza4/mediacentermaster#1874]
Here is the log.
Attempted to process files once with fetcher set to v3, once with v2 and once with imdb.
Previous to recent changes to TVDB, the daily shows have properly been found and renamed for more than a year.

6:11 PM :: MCM:  Processing new downloads in: N:\uTorrent\Completed Downloads
6:11 PM :: -----------------------------------------------------------------------------------------
6:11 PM :: MCM:  Now working on the.daily.show.2019.10.17.taika.waititi.web.x264-tbs.mkv...
6:11 PM ::  tv  db   Searching by air date: 2019-10-17
6:11 PM :: MCM:  ... this is a T.V. show episode (detected using quick method)
6:11 PM :: MCM:  I'm not sure if this file is a T.V. episode or a movie -- I can't detect it as either:  the.daily.show.2019.10.17.taika.waititi.web.x264-tbs.mkv
6:11 PM :: MCM:  The file is not named in a way I understand.  If this is a T.V. episode and you have a scan folder set up for it, then you may want to add a T.V. detection override settings to manually map a series description to its ID.
6:11 PM :: -----------------------------------------------------------------------------------------
6:12 PM :: MCM:  Processing new downloads in: N:\uTorrent\Completed Downloads
6:12 PM :: -----------------------------------------------------------------------------------------
6:12 PM :: MCM:  Now working on the.daily.show.2019.10.17.taika.waititi.web.x264-tbs.mkv...
6:12 PM :: thetvdb.com  Searching by air date: 2019-10-17
6:12 PM :: MCM:  ... this is a T.V. show episode (detected using quick method)
6:12 PM :: MCM:  I'm not sure if this file is a T.V. episode or a movie -- I can't detect it as either:  the.daily.show.2019.10.17.taika.waititi.web.x264-tbs.mkv
6:12 PM :: MCM:  The file is not named in a way I understand.  If this is a T.V. episode and you have a scan folder set up for it, then you may want to add a T.V. detection override settings to manually map a series description to its ID.
6:12 PM :: -----------------------------------------------------------------------------------------
6:12 PM :: MCM:  Processing new downloads in: N:\uTorrent\Completed Downloads
6:12 PM :: -----------------------------------------------------------------------------------------
6:12 PM :: MCM:  Now working on the.daily.show.2019.10.17.taika.waititi.web.x264-tbs.mkv...
6:12 PM :: IMDb.com:  Searching by air date: 2019-10-17
6:12 PM :: IMDb.com:  ... no matches
6:12 PM :: MCM:  ... this is a T.V. show episode (detected using quick method)
6:12 PM :: MCM:  I'm not sure if this file is a T.V. episode or a movie -- I can't detect it as either:  the.daily.show.2019.10.17.taika.waititi.web.x264-tbs.mkv
6:12 PM :: MCM:  The file is not named in a way I understand.  If this is a T.V. episode and you have a scan folder set up for it, then you may want to add a T.V. detection override settings to manually map a series description to its ID.

**Comment by psouza4** [comment]
This bug report is missing the link to the forums where it was confirmed and I also see no support information.  I can't do anything with just a log.  This isn't even a developer debug log.  Please follow the posted rules.

**Comment by psouza4** [comment]
Other reports of this issue here:
http://forums.mediacentermaster.com/viewtopic.php?f=4&t=19723

Fixed in version 2.19 build 32919.1065 (2.19.32919.1065).
