### ISSUE TITLE
Pete the creator of MCM is completely MIA

### ISSUE THREAD

**Issue by MCMuser1** [psouza4/mediacentermaster#1883]
It'd be great if you'd check in, both here and the MCM forums and let your paid users know what's going on.  If you have, or are going to, abandoned MCM some sort of communication would be nice.  I love the product and paid for a "lifetime" subscription but if we have to look for something new it'd be nice to be told that rather than everything just quit working one day.  If you are continuing on with it that'd be awesome to hear too.

**Comment by psouza4** [comment]
I'm replying to this so that you get an e-mailed update, but this sort of things really doesn't belong here.  I am not 'moving on' and still regularly self-use the software and will continue to update and support it.
