### ISSUE TITLE
MCMStubLauncher has stopped working

### ISSUE THREAD

**Issue by psouza4** [psouza4/mediacentermaster#770]
Originally reported on Google Code with ID 770

```
Hi I had my MEdia Center Master running for a while now and noticed yesterday that there
was an update
On the attempt to update I get MCMStubLauncher has stopped working and the 
I have done the procedure explained in this forum post to no success:
http://forums.mediacentermaster.com/viewtopic.php?f=6&t=1524

I even went as far as deleting the entire Peter Souza folder and still the problem
persists
Please help
```

Reported by `toufeeqt` on 2011-09-18 10:17:13

**Comment by Deacon-Wolf** [comment]
Hi thankyou for this program i have used it for many years now. I have always been able to fix any issue i have had until now.
The error i get is from the lastest version:

MCMStubLauncher has stopped working

Is there a way to repair this?

**Comment by Happy2Play** [comment]
Have you tried uninstalling and reinstalling?

**Comment by Deacon-Wolf** [comment]
Yes sure have. Is there anything else I can try?

**Comment by psouza4** [comment]
You definitely need to open a support topic at the official community support forums with any details on the crash.  You may have to enable error reporting or check the Windows event log if there isn't specifically any error message visible during the stop message.
